//! Node configuration for slay3rd consensus node.
//!
//! `NodeConfig` is loaded from a TOML file at startup and provides all runtime
//! parameters: validator keys, peer addresses, listen addresses, genesis file
//! path, DKG key material, and consensus timeouts.

use serde::{Deserialize, Serialize};

/// Configuration for a single peer in the validator set.
///
/// Each peer entry in `[[peers]]` specifies the network address and the
/// Ed25519 public key used for authenticated P2P.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PeerConfig {
    /// Network address in "host:port" format — must be parseable as a `SocketAddr`.
    pub address: String,

    /// Ed25519 public key hex string for authenticated P2P identity verification.
    pub public_key: String,
}

/// Configuration for a single slay3rd consensus node.
///
/// Load from a TOML file with `NodeConfig::from_file(path)`.
/// Key material (BLS shares, Ed25519 identity key) is stored in separate
/// JSON files whose paths are referenced here.
///
/// All storage paths are derived from `data_dir`:
/// - WAL: `{data_dir}/wal`
/// - App state (RocksDB): `{data_dir}/app`
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NodeConfig {
    /// This node's validator index (0-based) in the static validator set.
    pub validator_index: usize,

    /// Chain ID for the Layer network (e.g., "slay3r-testnet-1").
    pub chain_id: String,

    /// Listen address for P2P networking (e.g., "0.0.0.0:7001").
    pub p2p_listen: String,

    /// Listen address for gRPC (e.g., "0.0.0.0:9090").
    pub grpc_listen: String,

    /// Peer configurations for other validators.
    /// Each entry has `address = "host:port"` and `public_key = "ed25519_hex"`.
    /// For a 3-node testnet, this should contain 2 entries (not including self).
    pub peers: Vec<PeerConfig>,

    /// Path to the BLS key material JSON file.
    /// Generated by `tools/generate-testnet-keys`.
    /// Contains: bls_secret_share, bls_public_share, threshold_public_key, validator_set.
    pub bls_key_path: String,

    /// Path to the Ed25519 node identity key JSON file.
    /// Contains the hex-encoded private key used for P2P authentication.
    pub identity_key_path: String,

    /// Base directory for all persistent data.
    /// WAL is stored at `{data_dir}/wal`, app state at `{data_dir}/app`.
    pub data_dir: String,

    /// Path to genesis JSON file.
    pub genesis_path: String,

    /// Maximum pending transactions in mempool.
    pub mempool_max_pending: usize,

    /// Leader timeout in milliseconds.
    /// Time to wait for a leader to propose a payload before skipping the view.
    pub leader_timeout_ms: u64,

    /// Certification timeout in milliseconds.
    /// Time to wait for certification progress in a view before attempting to skip.
    pub certification_timeout_ms: u64,
}

impl Default for NodeConfig {
    fn default() -> Self {
        NodeConfig {
            validator_index: 0,
            chain_id: "slay3r-testnet-1".to_string(),
            p2p_listen: "0.0.0.0:7001".to_string(),
            grpc_listen: "0.0.0.0:9090".to_string(),
            peers: vec![],
            bls_key_path: "keys/bls.json".to_string(),
            identity_key_path: "keys/identity.json".to_string(),
            data_dir: "data".to_string(),
            genesis_path: "config/genesis.json".to_string(),
            mempool_max_pending: 10_000,
            leader_timeout_ms: 3_000,
            certification_timeout_ms: 5_000,
        }
    }
}

impl NodeConfig {
    /// Load config from a TOML file at the given path.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be read or parsed as valid TOML.
    pub fn from_file(path: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let contents = std::fs::read_to_string(path)?;
        let config: NodeConfig = toml::from_str(&contents)?;
        Ok(config)
    }

    /// Returns the WAL directory path, computed as `{data_dir}/wal`.
    pub fn wal_path(&self) -> String {
        format!("{}/wal", self.data_dir)
    }

    /// Returns the app data directory path, computed as `{data_dir}/app`.
    pub fn app_data_path(&self) -> String {
        format!("{}/app", self.data_dir)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let cfg = NodeConfig::default();
        assert_eq!(cfg.validator_index, 0);
        assert_eq!(cfg.chain_id, "slay3r-testnet-1");
        assert_eq!(cfg.mempool_max_pending, 10_000);
        assert_eq!(cfg.leader_timeout_ms, 3_000);
        assert_eq!(cfg.certification_timeout_ms, 5_000);
        assert_eq!(cfg.wal_path(), "data/wal");
        assert_eq!(cfg.app_data_path(), "data/app");
    }

    #[test]
    fn test_config_roundtrip() {
        let cfg = NodeConfig {
            validator_index: 1,
            chain_id: "test-chain".to_string(),
            p2p_listen: "127.0.0.1:9001".to_string(),
            grpc_listen: "127.0.0.1:9090".to_string(),
            peers: vec![
                PeerConfig {
                    address: "127.0.0.1:9002".to_string(),
                    public_key: "aabb".to_string(),
                },
                PeerConfig {
                    address: "127.0.0.1:9003".to_string(),
                    public_key: "ccdd".to_string(),
                },
            ],
            bls_key_path: "keys/bls.json".to_string(),
            identity_key_path: "keys/identity.json".to_string(),
            data_dir: "testdata".to_string(),
            genesis_path: "genesis.json".to_string(),
            mempool_max_pending: 5_000,
            leader_timeout_ms: 1_000,
            certification_timeout_ms: 2_000,
        };
        let toml_str = toml::to_string(&cfg).expect("serialization should succeed");
        let decoded: NodeConfig = toml::from_str(&toml_str).expect("deserialization should succeed");
        assert_eq!(decoded.validator_index, 1);
        assert_eq!(decoded.chain_id, "test-chain");
        assert_eq!(decoded.peers.len(), 2);
        assert_eq!(decoded.peers[0].address, "127.0.0.1:9002");
        assert_eq!(decoded.peers[0].public_key, "aabb");
        assert_eq!(decoded.data_dir, "testdata");
        assert_eq!(decoded.wal_path(), "testdata/wal");
        assert_eq!(decoded.app_data_path(), "testdata/app");
    }

    #[test]
    fn test_config_with_peers_toml_roundtrip() {
        let toml_str = r#"
validator_index = 0
chain_id = "slay3r-testnet-1"
p2p_listen = "0.0.0.0:7001"
grpc_listen = "0.0.0.0:9090"
data_dir = "./data/node0"
bls_key_path = "keys/node0.json"
identity_key_path = "keys/node0.json"
genesis_path = "config/genesis.json"
mempool_max_pending = 10000
leader_timeout_ms = 3000
certification_timeout_ms = 5000

[[peers]]
address = "127.0.0.1:7002"
public_key = "aabbccdd"

[[peers]]
address = "127.0.0.1:7003"
public_key = "eeff0011"
"#;
        let cfg: NodeConfig = toml::from_str(toml_str).expect("TOML parse failed");
        assert_eq!(cfg.peers.len(), 2);
        assert_eq!(cfg.peers[0].address, "127.0.0.1:7002");
        assert_eq!(cfg.peers[0].public_key, "aabbccdd");
        assert_eq!(cfg.peers[1].address, "127.0.0.1:7003");
        assert_eq!(cfg.peers[1].public_key, "eeff0011");
        assert_eq!(cfg.data_dir, "./data/node0");
        assert_eq!(cfg.wal_path(), "./data/node0/wal");
        assert_eq!(cfg.app_data_path(), "./data/node0/app");
    }
}
