//! Node configuration for slay3rd consensus node.
//!
//! `NodeConfig` is loaded from a TOML file at startup and provides all runtime
//! parameters: validator keys, peer addresses, listen addresses, genesis file
//! path, DKG key material, and consensus timeouts.

use serde::{Deserialize, Serialize};

/// Configuration for a single slay3rd consensus node.
///
/// Load from a TOML file with `NodeConfig::from_file(path)`.
/// Key material (BLS shares, Ed25519 identity key) is stored in separate
/// JSON files whose paths are referenced here.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NodeConfig {
    /// This node's validator index (0-based) in the static validator set.
    pub validator_index: usize,

    /// Chain ID for the Layer network (e.g., "slay3r-testnet-1").
    pub chain_id: String,

    /// Listen address for P2P networking (e.g., "0.0.0.0:26656").
    pub p2p_listen: String,

    /// Listen address for gRPC (e.g., "0.0.0.0:9090").
    pub grpc_listen: String,

    /// Peer addresses for other validators.
    /// Format: "host:port" for each peer.
    /// For a 3-node testnet, this should contain 2 entries (not including self).
    pub peers: Vec<String>,

    /// Path to the BLS key material JSON file.
    /// Generated by `tools/generate-testnet-keys`.
    /// Contains: bls_secret_share, bls_public_share, threshold_public_key, validator_set.
    pub bls_key_path: String,

    /// Path to the Ed25519 node identity key JSON file.
    /// Contains the hex-encoded private key used for P2P authentication.
    pub identity_key_path: String,

    /// Path to RocksDB storage directory.
    /// Set to `None` to use in-memory storage (useful for testing).
    pub rocksdb_path: Option<String>,

    /// Path to the WAL directory for consensus state.
    /// Used by commonware-storage Journal for crash recovery.
    pub wal_path: String,

    /// Path to genesis JSON file.
    pub genesis_path: String,

    /// Maximum pending transactions in mempool.
    pub mempool_max_pending: usize,

    /// Leader timeout in milliseconds.
    /// Time to wait for a leader to propose a payload before skipping the view.
    pub leader_timeout_ms: u64,

    /// Certification timeout in milliseconds.
    /// Time to wait for certification progress in a view before attempting to skip.
    pub certification_timeout_ms: u64,
}

impl Default for NodeConfig {
    fn default() -> Self {
        NodeConfig {
            validator_index: 0,
            chain_id: "slay3r-testnet-1".to_string(),
            p2p_listen: "0.0.0.0:26656".to_string(),
            grpc_listen: "0.0.0.0:9090".to_string(),
            peers: vec![],
            bls_key_path: "keys/bls.json".to_string(),
            identity_key_path: "keys/identity.json".to_string(),
            rocksdb_path: None,
            wal_path: "data/wal".to_string(),
            genesis_path: "config/genesis.json".to_string(),
            mempool_max_pending: 10_000,
            leader_timeout_ms: 3_000,
            certification_timeout_ms: 5_000,
        }
    }
}

impl NodeConfig {
    /// Load config from a TOML file at the given path.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be read or parsed as valid TOML.
    pub fn from_file(path: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let contents = std::fs::read_to_string(path)?;
        let config: NodeConfig = toml::from_str(&contents)?;
        Ok(config)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let cfg = NodeConfig::default();
        assert_eq!(cfg.validator_index, 0);
        assert_eq!(cfg.chain_id, "slay3r-testnet-1");
        assert_eq!(cfg.mempool_max_pending, 10_000);
        assert_eq!(cfg.leader_timeout_ms, 3_000);
        assert_eq!(cfg.certification_timeout_ms, 5_000);
    }

    #[test]
    fn test_config_roundtrip() {
        let cfg = NodeConfig {
            validator_index: 1,
            chain_id: "test-chain".to_string(),
            p2p_listen: "127.0.0.1:9001".to_string(),
            grpc_listen: "127.0.0.1:9090".to_string(),
            peers: vec!["127.0.0.1:9002".to_string(), "127.0.0.1:9003".to_string()],
            bls_key_path: "keys/bls.json".to_string(),
            identity_key_path: "keys/identity.json".to_string(),
            rocksdb_path: None,
            wal_path: "data/wal".to_string(),
            genesis_path: "genesis.json".to_string(),
            mempool_max_pending: 5_000,
            leader_timeout_ms: 1_000,
            certification_timeout_ms: 2_000,
        };
        let toml_str = toml::to_string(&cfg).expect("serialization should succeed");
        let decoded: NodeConfig = toml::from_str(&toml_str).expect("deserialization should succeed");
        assert_eq!(decoded.validator_index, 1);
        assert_eq!(decoded.chain_id, "test-chain");
        assert_eq!(decoded.peers.len(), 2);
    }
}
