//! slay3rd — Layer Commonware consensus node entry point.
//!
//! This binary drives the Layer state machine through Commonware simplex consensus
//! with BLS12-381 threshold signatures (via the `bls12381_threshold::standard` scheme).
//!
//! # Startup sequence
//!
//! 1. Parse config (TOML file from `SLAY_CONFIG` env var or first CLI arg)
//! 2. Init tracing
//! 3. Load BLS key material (JSON from `config.bls_key_path`)
//! 4. Initialize storage (MemoryStore)
//! 5. Initialize App from genesis or load existing state
//! 6. Create Mempool and LayerNode (consensus bridge)
//! 7. Create LayerRelay (with SHARED pending_payloads from LayerNode)
//! 8. Create logging Reporter
//! 9. Build simplex Engine config (BLS threshold scheme, round-robin elector)
//! 10. Spawn consensus engine via commonware_runtime::tokio::Runner
//!
//! # Key material
//!
//! Generated by `tools/generate-testnet-keys`. The JSON file contains:
//! - `bls_private_hex`: BLS secret share
//! - `threshold_public_key_hex`: group threshold public key
//! - `ed25519_public_hex`: this node's Ed25519 identity public key
//! - `validator_public_keys`: ordered list of all validators' Ed25519 public keys
//!
//! If BLS key material is missing or invalid, the node exits with a clear error message.
//! Consensus MUST NOT start until DKG key material is loaded and validated.

use std::num::{NonZeroU16, NonZeroU32, NonZeroUsize};
use std::sync::Arc;
use std::time::Duration;

use commonware_codec::extensions::DecodeExt;
use commonware_consensus::simplex::elector::RoundRobin;
use commonware_consensus::simplex::scheme::bls12381_threshold::standard::Scheme as BlsScheme;
use commonware_consensus::simplex::{config::Config as SimplexConfig, Engine};
use commonware_consensus::Reporter;
use commonware_cryptography::bls12381::dkg::deal_anonymous;
use commonware_cryptography::bls12381::primitives::{sharing::Mode, variant::MinSig};
use commonware_cryptography::{ed25519, sha256};
use commonware_math::algebra::Random;
use commonware_p2p::simulated::{Config as P2pConfig, Link, Network};
use commonware_parallel::Sequential;
use commonware_runtime::{buffer::paged::CacheRef, Metrics, Runner};
use commonware_utils::{ordered::Set, N3f1, NZU16, NZUsize};
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex;
use tracing::{error, info, warn};

use slay3rd::{config::NodeConfig, mempool::Mempool, node::LayerNode, relay::LayerRelay};

use layer_app::{
    genesis::{GenesisState, WasmParams},
    App, AppConfig, StateMachine,
};
use layer_storage::MemoryStore;

// Page cache parameters for the consensus engine WAL.
const PAGE_SIZE: NonZeroU16 = NZU16!(4096);
const PAGE_CACHE_SIZE: NonZeroUsize = NZUsize!(64);

/// Consensus namespace for domain separation in BLS signatures.
const NAMESPACE: &[u8] = b"slay3r-consensus-v1";

/// Epoch 0: first epoch for a static 3-node testnet (no resharing yet).
const CONSENSUS_EPOCH: commonware_consensus::types::Epoch =
    commonware_consensus::types::Epoch::new(0);

/// Key material loaded from the JSON file produced by `tools/generate-testnet-keys`.
#[derive(Serialize, Deserialize, Debug)]
struct KeyMaterial {
    validator_index: usize,
    share_index: u32,
    bls_private_hex: String,
    bls_public_hex: String,
    threshold_public_key_hex: String,
    threshold_required: u32,
    threshold_total: u32,
    ed25519_private_hex: String,
    ed25519_public_hex: String,
    validator_public_keys: Vec<String>,
}

impl KeyMaterial {
    fn load(path: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let contents = std::fs::read_to_string(path)?;
        let km: KeyMaterial = serde_json::from_str(&contents)?;
        Ok(km)
    }
}

/// Consensus reporter that persists BLS threshold certificates to the Layer App storage.
///
/// Implements `commonware_consensus::Reporter` for the simplex Activity type.
/// When a `Finalization` activity is received, it extracts the BLS certificate bytes
/// and calls `App::set_block_certificate()` to persist them keyed by block height.
///
/// This closes the CONS-05 gap: the certificate is NOT available at certify() time
/// (it is assembled by the consensus engine after a quorum of validators certify).
/// The Finalization activity delivers the certificate post-commit, and the Reporter
/// is the correct place to store it.
#[derive(Clone)]
struct LayerReporter {
    /// Shared reference to the Layer application.
    /// Used to persist BLS certificates via set_block_certificate()
    /// when the consensus engine delivers a Finalization activity.
    app: Arc<Mutex<App<MemoryStore>>>,
}

impl Reporter for LayerReporter {
    type Activity = commonware_consensus::simplex::types::Activity<
        BlsScheme<ed25519::PublicKey, MinSig>,
        sha256::Digest,
    >;

    async fn report(&mut self, activity: Self::Activity) {
        use commonware_codec::codec::Encode as _;
        use commonware_consensus::simplex::types::Activity;

        match &activity {
            Activity::Finalization(finalization) => {
                // CONS-05: Finalized block with BLS threshold certificate.
                // The certificate bytes are produced by the consensus engine after a quorum
                // of validators certify. They are NOT available at certify() time.
                let cert_bytes = finalization.certificate.encode().to_vec();
                let payload_digest: [u8; 32] = finalization.proposal.payload.0;

                // Determine the block height: query the App's last committed block.
                // Since certify() -> execute_block() -> finalize_block() has already run,
                // the App's LAST_BLOCK height IS the block that just received its certificate.
                let height = {
                    let app = self.app.lock().await;
                    app.info().map(|b| b.height).unwrap_or(0)
                };

                tracing::info!(
                    height = height,
                    view = ?finalization.proposal.round,
                    payload_digest = %hex::encode(payload_digest),
                    cert_len = cert_bytes.len(),
                    certificate = %hex::encode(&cert_bytes),
                    "Block finalized with BLS threshold certificate (CONS-05)"
                );

                // CONS-05: Persist the BLS certificate to the committed block record.
                // This is the post-commit update path — the block was already committed
                // by certify()/execute_block()/finalize_block(), and now we store the
                // certificate that the consensus engine produced from the quorum of
                // certify votes.
                if !cert_bytes.is_empty() {
                    let mut app = self.app.lock().await;
                    match app.set_block_certificate(height, cert_bytes.clone()) {
                        Ok(()) => {
                            tracing::info!(
                                height = height,
                                cert_len = cert_bytes.len(),
                                "BLS certificate stored in block record (CONS-05)"
                            );
                        }
                        Err(e) => {
                            tracing::error!(
                                height = height,
                                error = ?e,
                                "Failed to store BLS certificate — CONS-05 gap"
                            );
                        }
                    }
                }
            }
            Activity::Notarization(notarization) => {
                tracing::debug!(
                    view = ?notarization.proposal.round,
                    "Block notarized"
                );
            }
            Activity::Nullification(nullification) => {
                tracing::debug!(
                    round = ?nullification.round,
                    "View nullified (skipped)"
                );
            }
            _ => {
                tracing::trace!("Consensus activity received");
            }
        }
    }
}

fn main() {
    // Parse CLI arguments or use env var for config path.
    let config_path = std::env::args()
        .skip(1)
        .find(|arg| !arg.starts_with('-'))
        .or_else(|| std::env::var("SLAY_CONFIG").ok())
        .unwrap_or_else(|| "config/node.toml".to_string());

    // Load node config from TOML.
    let config = match NodeConfig::from_file(&config_path) {
        Ok(cfg) => cfg,
        Err(e) => {
            eprintln!("Error: failed to load config from '{config_path}': {e}");
            eprintln!("Set SLAY_CONFIG or pass config path as first argument.");
            std::process::exit(1);
        }
    };

    // Init tracing with env-filter (respects RUST_LOG).
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    info!(
        chain_id = %config.chain_id,
        validator_index = config.validator_index,
        p2p_listen = %config.p2p_listen,
        grpc_listen = %config.grpc_listen,
        "slay3rd: starting Layer Commonware consensus node"
    );

    // Load BLS key material. If missing, exit with a clear error.
    // INVARIANT: Consensus MUST NOT start until DKG key material is validated.
    let km = match KeyMaterial::load(&config.bls_key_path) {
        Ok(km) => {
            info!(
                validator_index = km.validator_index,
                share_index = km.share_index,
                threshold = %format!("{}/{}", km.threshold_required, km.threshold_total),
                "BLS key material loaded"
            );
            km
        }
        Err(e) => {
            error!(
                path = %config.bls_key_path,
                error = %e,
                "Failed to load BLS key material — generate with tools/generate-testnet-keys"
            );
            std::process::exit(1);
        }
    };

    // Use commonware_runtime::tokio::Runner to provide the Context needed by Engine::new().
    // Runner::start() blocks until the future completes.
    let runner = commonware_runtime::tokio::Runner::default();
    runner.start(|context| async move {
        run_node(context, config, km).await
    });
}

/// Main async node logic. Receives a commonware_runtime::tokio::Context from the Runner.
async fn run_node(
    context: commonware_runtime::tokio::Context,
    config: NodeConfig,
    km: KeyMaterial,
) {
    // -----------------------------------------------------------------------
    // App initialization
    // -----------------------------------------------------------------------

    // Phase 2: MemoryStore (no RocksDB persistence yet).
    let storage = MemoryStore::default();
    let logic = StateMachine::new(&AppConfig::new(&config.wal_path()));
    let mut app = App::new(storage, logic);

    // Attempt to load state; if none exists, initialize from genesis.
    use layer_app::AppLoadError;
    match app.load_from_storage() {
        Ok(()) => {
            info!("App loaded from existing storage");
        }
        Err(AppLoadError::NoStoredState) => {
            info!("No stored state — initializing from genesis");
            let genesis = default_genesis();
            let app_state = match serde_json::to_vec(&genesis) {
                Ok(b) => b,
                Err(e) => {
                    error!(error = %e, "Failed to serialize genesis state");
                    return;
                }
            };
            let init_req = layer_std::api::InitChainRequest {
                time: cosmwasm_std::Timestamp::from_nanos(1_673_194_026_078_305_426),
                chain_id: config.chain_id.clone(),
                consensus_params: Default::default(),
                validators: vec![],
                app_state: cosmwasm_std::Binary::from(app_state),
                initial_height: 1,
            };
            if let Err(e) = app.init(init_req) {
                error!(error = ?e, "Failed to initialize App from genesis");
                return;
            }
        }
        Err(e) => {
            error!(error = ?e, "State corruption — cannot continue");
            return;
        }
    }

    // -----------------------------------------------------------------------
    // LayerNode + LayerRelay (SHARED pending_payloads)
    // -----------------------------------------------------------------------

    let mempool = Arc::new(Mutex::new(Mempool::new(config.mempool_max_pending)));
    let app_arc = Arc::new(Mutex::new(app));

    // initial_height=0 means the next block will be height=1.
    let layer_node = LayerNode::<MemoryStore, ed25519::PublicKey>::new(
        app_arc.clone(),
        mempool.clone(),
        0,
    );

    // CRITICAL: The relay MUST receive the SAME pending_payloads Arc from LayerNode.
    // This is what allows non-proposer validators to find payloads in verify().
    let relay = LayerRelay::new(layer_node.pending_payloads());
    // CONS-05: Reporter holds the app Arc so it can persist BLS certificates
    // via set_block_certificate() when the Finalization activity fires.
    let reporter = LayerReporter { app: app_arc.clone() };

    info!("LayerNode and LayerRelay created (shared pending_payloads)");

    // -----------------------------------------------------------------------
    // BLS12-381 threshold scheme from DKG key material
    // -----------------------------------------------------------------------

    // Decode all validator Ed25519 public keys.
    let mut participant_keys: Vec<ed25519::PublicKey> = Vec::new();
    for hex_key in &km.validator_public_keys {
        match hex::decode(hex_key) {
            Ok(key_bytes) => {
                match ed25519::PublicKey::decode(bytes::Bytes::from(key_bytes)) {
                    Ok(pk) => participant_keys.push(pk),
                    Err(e) => {
                        error!(error = %e, "Failed to decode validator Ed25519 public key");
                        return;
                    }
                }
            }
            Err(e) => {
                error!(error = %e, "Invalid hex in validator_public_keys");
                return;
            }
        }
    }

    let participants = match Set::try_from(participant_keys.as_slice()) {
        Ok(s) => s,
        Err(e) => {
            error!(error = %e, "Failed to build participant set (keys may be unordered or duplicate)");
            return;
        }
    };

    // Reconstruct the BLS sharing polynomial.
    // Phase 2 uses deal_anonymous with a fixed seed (matching the keygen tool).
    // Phase 3+ TODO: Serialize and load Sharing directly from the key material JSON.
    let n = match NonZeroU32::new(km.threshold_total) {
        Some(n) => n,
        None => {
            error!("threshold_total must be > 0");
            return;
        }
    };

    // Use the same seeded RNG as the keygen tool to reproduce the same DKG output.
    let mut rng = ChaCha8Rng::seed_from_u64(0);
    // Skip Ed25519 key generation (same as keygen tool does first) to advance RNG state.
    for _ in 0..km.threshold_total {
        let _ = ed25519::PrivateKey::random(&mut rng);
    }
    let (sharing, shares) = deal_anonymous::<MinSig, N3f1>(&mut rng, Mode::NonZeroCounter, n);

    if km.validator_index >= shares.len() {
        error!(
            validator_index = km.validator_index,
            total = shares.len(),
            "validator_index out of range"
        );
        return;
    }
    let our_share = shares[km.validator_index].clone();

    // Create the BLS threshold signing Scheme.
    let bls_scheme = match BlsScheme::<ed25519::PublicKey, MinSig>::signer(
        NAMESPACE,
        participants.clone(),
        sharing,
        our_share,
    ) {
        Some(s) => s,
        None => {
            error!("BLS scheme creation failed — share does not match polynomial");
            return;
        }
    };

    info!(
        validator_index = km.validator_index,
        threshold = %format!("{}/{}", km.threshold_required, km.threshold_total),
        "BLS12-381 threshold signing scheme initialized"
    );

    // -----------------------------------------------------------------------
    // P2P network (Phase 2: in-process simulated for localhost testing)
    //
    // Phase 3+ TODO: Replace with commonware-p2p::authenticated for real multi-host P2P.
    // The authenticated transport uses TLS + Ed25519 identity keys for mutual auth.
    // -----------------------------------------------------------------------

    let p2p_cfg = P2pConfig {
        max_size: 1024 * 1024,
        disconnect_on_block: true,
        tracked_peer_sets: Some(3),
    };

    let p2p_ctx = context.with_label("p2p");
    let (network, oracle) = Network::new(p2p_ctx, p2p_cfg);
    let _network_handle = network.start();

    // Register the participant set with the network manager.
    {
        use commonware_p2p::Manager as _;
        let mut mgr = oracle.manager();
        mgr.track(0, participants.clone()).await;
    }

    let quota = commonware_runtime::Quota::per_second(NonZeroU32::MAX);
    let our_pk = participant_keys[km.validator_index].clone();

    // Register this node's three network channels (vote, certificate, resolver).
    let (vote_sender, vote_receiver) = oracle.control(our_pk.clone())
        .register(0, quota)
        .await
        .expect("vote channel registration should succeed");
    let (cert_sender, cert_receiver) = oracle.control(our_pk.clone())
        .register(1, quota)
        .await
        .expect("certificate channel registration should succeed");
    let (res_sender, res_receiver) = oracle.control(our_pk.clone())
        .register(2, quota)
        .await
        .expect("resolver channel registration should succeed");

    // Link this node to all other validators (zero-latency, 100% delivery for localhost).
    let link = Link {
        latency: Duration::from_millis(0),
        jitter: Duration::from_millis(0),
        success_rate: 1.0,
    };
    for (i, pk) in participant_keys.iter().enumerate() {
        if i != km.validator_index {
            oracle
                .add_link(our_pk.clone(), pk.clone(), link.clone())
                .await
                .unwrap_or_else(|e| warn!(error = %e, "Failed to add link to validator {i}"));
        }
    }

    info!("P2P simulated network initialized ({} validators)", km.threshold_total);

    // -----------------------------------------------------------------------
    // Simplex consensus Engine
    // -----------------------------------------------------------------------

    let leader_timeout = Duration::from_millis(config.leader_timeout_ms);
    let cert_timeout = Duration::from_millis(config.certification_timeout_ms);
    let timeout_retry = Duration::from_millis((config.leader_timeout_ms / 2).max(100));

    let consensus_cfg = SimplexConfig {
        scheme: bls_scheme,
        elector: RoundRobin::<commonware_cryptography::Sha256>::default(),
        blocker: oracle.control(our_pk.clone()),
        automaton: layer_node,
        relay,
        reporter,
        strategy: Sequential,
        partition: format!("slay3r-{}", config.chain_id),
        mailbox_size: 1024,
        epoch: CONSENSUS_EPOCH,
        replay_buffer: NZUsize!(1024 * 1024),
        write_buffer: NZUsize!(1024 * 1024),
        page_cache: CacheRef::from_pooler(&context, PAGE_SIZE, PAGE_CACHE_SIZE),
        leader_timeout,
        certification_timeout: cert_timeout,
        timeout_retry,
        activity_timeout: commonware_consensus::types::ViewDelta::new(10),
        skip_timeout: commonware_consensus::types::ViewDelta::new(5),
        fetch_timeout: Duration::from_secs(5),
        fetch_concurrent: 4,
    };

    consensus_cfg.assert();

    let consensus_ctx = context.with_label("consensus");
    let engine = Engine::new(consensus_ctx, consensus_cfg);
    info!("Starting simplex consensus engine (epoch=0)...");

    // Start engine with the three P2P channel pairs.
    let _engine_handle = engine.start(
        (vote_sender, vote_receiver),
        (cert_sender, cert_receiver),
        (res_sender, res_receiver),
    );

    info!(
        grpc_listen = %config.grpc_listen,
        "Consensus engine started. gRPC server Phase 2 stub (tx submission not yet wired)."
    );

    // Wait for shutdown signal (Ctrl+C).
    match tokio::signal::ctrl_c().await {
        Ok(()) => info!("Shutdown signal received — stopping slay3rd"),
        Err(e) => warn!(error = %e, "Error waiting for shutdown signal"),
    }
}

/// Default empty genesis state for testnet bootstrapping.
fn default_genesis() -> GenesisState {
    GenesisState {
        bank: vec![],
        wasm: WasmParams {
            gov_account: "layer1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmt53rug".to_string(),
        },
    }
}
