//! slay3rd — Layer Commonware consensus node entry point.
//!
//! This binary drives the Layer state machine through Commonware simplex consensus
//! with BLS12-381 threshold signatures (via the `bls12381_threshold::standard` scheme).
//!
//! # Startup sequence
//!
//! 1. Parse config (TOML file from `SLAY_CONFIG` env var or first CLI arg)
//! 2. Init tracing
//! 3. Load BLS key material (JSON from `config.bls_key_path`)
//! 4. Initialize storage (RocksDB with `rocksdb` feature, MemoryStore otherwise)
//! 5. Initialize App from genesis or load existing state
//! 6. Create Mempool and LayerNode (consensus bridge)
//! 7. Create LayerRelay (with SHARED pending_payloads from LayerNode)
//! 8. Create logging Reporter
//! 9. Spawn gRPC server with Cosmos SDK query dispatch
//! 10. Build authenticated P2P network (real cross-process TLS + Ed25519)
//! 11. Build simplex Engine config (BLS threshold scheme, round-robin elector)
//! 12. Spawn consensus engine via commonware_runtime::tokio::Runner
//!
//! # Key material
//!
//! Generated by `tools/generate-testnet-keys`. The JSON file contains:
//! - `bls_private_hex`: BLS secret share
//! - `threshold_public_key_hex`: group threshold public key
//! - `ed25519_public_hex`: this node's Ed25519 identity public key
//! - `ed25519_private_hex`: this node's Ed25519 identity private key (for P2P auth)
//! - `validator_public_keys`: ordered list of all validators' Ed25519 public keys
//!
//! If BLS key material is missing or invalid, the node exits with a clear error message.
//! Consensus MUST NOT start until DKG key material is loaded and validated.

use std::marker::PhantomData;
use std::net::SocketAddr;
use std::num::{NonZeroU16, NonZeroU32, NonZeroUsize};
use std::sync::Arc;
use std::time::Duration;

use commonware_codec::extensions::DecodeExt;
use commonware_codec::Read;
use commonware_consensus::simplex::elector::RoundRobin;
use commonware_consensus::simplex::scheme::bls12381_threshold::standard::Scheme as BlsScheme;
use commonware_consensus::simplex::{config::Config as SimplexConfig, Engine};
use commonware_consensus::Reporter;
use commonware_cryptography::bls12381::dkg::deal_anonymous;
use commonware_cryptography::bls12381::primitives::{
    group::Share,
    sharing::{Mode, ModeVersion, Sharing},
    variant::MinSig,
};
use commonware_cryptography::{ed25519, sha256};
use commonware_math::algebra::Random;
use commonware_p2p::authenticated::lookup::{Config as P2pConfig, Network};
use commonware_p2p::{Address as P2pAddress, AddressableManager, Recipients, Receiver, Sender as P2pSender};
use commonware_parallel::Sequential;
use commonware_runtime::{buffer::paged::CacheRef, Metrics, Runner};
use commonware_utils::{ordered::Map, N3f1, NZU16, NZUsize};
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;
use serde::{Deserialize, Serialize};
use tokio::sync::{Mutex, RwLock};
use tonic::transport::Server as GrpcServer;
use tracing::{error, info, warn};

/// Channel-3 message tags: a full payload, a request for a payload by
/// digest, or a request for a contiguous range of payloads by height
/// (bulk backfill — the requester doesn't know digests yet).
const PAYLOAD_MSG_PUSH: u8 = 0;
const PAYLOAD_MSG_REQUEST: u8 = 1;
const PAYLOAD_MSG_REQUEST_RANGE: u8 = 2;

use junoclaw_mayo_verify::ParameterSet as _;

use slay3rd::{
    config::NodeConfig,
    grpc::LayerGrpcService,
    hybrid_scheme::HybridScheme,
    mempool::Mempool,
    node::{FetchRequest, LayerNode},
    relay::LayerRelay,
};

use layer_app::{
    genesis::{BankAccount, GenesisState, WasmParams},
    App, AppConfig, StateMachine,
};
use layer_storage::PersistentStorage;

#[cfg(feature = "rocksdb")]
use layer_storage::RockStore;
#[cfg(not(feature = "rocksdb"))]
use layer_storage::MemoryStore;

// Page cache parameters for the consensus engine WAL.
const PAGE_SIZE: NonZeroU16 = NZU16!(4096);
const PAGE_CACHE_SIZE: NonZeroUsize = NZUsize!(64);

/// Consensus namespace for domain separation in BLS signatures.
const NAMESPACE: &[u8] = b"slay3r-consensus-v1";

/// Epoch 0: first epoch for a static 3-node testnet (no resharing yet).
const CONSENSUS_EPOCH: commonware_consensus::types::Epoch =
    commonware_consensus::types::Epoch::new(0);

/// Key material loaded from the JSON file produced by `tools/generate-testnet-keys`.
#[derive(Serialize, Deserialize, Debug)]
struct KeyMaterial {
    validator_index: usize,
    share_index: u32,
    bls_private_hex: String,
    bls_public_hex: String,
    threshold_public_key_hex: String,
    threshold_required: u32,
    threshold_total: u32,
    ed25519_private_hex: String,
    ed25519_public_hex: String,
    validator_public_keys: Vec<String>,
    /// Serialized `Sharing` + `Share` from a Phase A ceremony (finalize).
    /// When present, the node uses them directly instead of re-dealing.
    #[serde(default)]
    sharing_hex: Option<String>,
    #[serde(default)]
    share_hex: Option<String>,
    /// Hybrid validator identity (docs/PQ_PROTOCOL_AUTH.md §3). Required iff
    /// `hybrid_consensus` is enabled in the node config.
    /// `mayo_variant` — "mayo2" (only supported variant, fixed-size sigs).
    #[serde(default)]
    mayo_variant: Option<String>,
    /// Hex-encoded MAYO secret seed (sriracha-mayo `SecretKey::from_seed` input).
    #[serde(default)]
    mayo_private_hex: Option<String>,
    /// Hex-encoded MAYO2 public key for this validator.
    #[serde(default)]
    mayo_public_hex: Option<String>,
    /// MAYO2 public keys of ALL validators in validator_index order — the
    /// same ordering convention as `validator_public_keys`. Sorted into
    /// binary order alongside the Ed25519 set at load time.
    #[serde(default)]
    validator_mayo_public_keys: Option<Vec<String>>,
}

impl KeyMaterial {
    fn load(path: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let contents = std::fs::read_to_string(path)?;
        let km: KeyMaterial = serde_json::from_str(&contents)?;
        Ok(km)
    }
}

/// Consensus reporter that persists BLS threshold certificates to the Layer App storage.
///
/// Generic over T: PersistentStorage to support both MemoryStore (tests) and
/// RockStore (production) without hardcoding the storage type.
///
/// Implements `commonware_consensus::Reporter` for the simplex Activity type.
/// When a `Finalization` activity is received, it extracts the BLS certificate bytes
/// and calls `App::set_block_certificate()` to persist them keyed by block height.
///
/// This closes the CONS-05 gap: the certificate is NOT available at certify() time
/// (it is assembled by the consensus engine after a quorum of validators certify).
/// The Finalization activity delivers the certificate post-commit, and the Reporter
/// is the correct place to store it.
///
/// The simplex voter awaits `report()` inline, so the reporter MUST NOT block:
/// it only enqueues finalizations for `run_executor`, which executes blocks
/// (possibly slow wasm, possibly waiting on payload fetches) off the
/// consensus path, in the order consensus finalized them.
#[derive(Clone)]
struct LayerReporter<S> {
    exec_tx: tokio::sync::mpsc::UnboundedSender<FinalizedBlock>,
    /// Certificate type flows through `Activity<S, _>`; PhantomData keeps the
    /// reporter generic over the consensus scheme (BLS-only or hybrid).
    _scheme: PhantomData<S>,
}

/// A finalization handed from the reporter to the executor.
struct FinalizedBlock {
    payload_digest: [u8; 32],
    cert_bytes: Vec<u8>,
    proposal_bytes: Vec<u8>,
    round: String,
}

/// Executes finalized blocks in order and persists their light-client records.
/// The ONLY place application state advances.
async fn run_executor<T: PersistentStorage + Send + Sync + 'static>(
    app: Arc<RwLock<App<T>>>,
    node: LayerNode<T, ed25519::PublicKey>,
    mut rx: tokio::sync::mpsc::UnboundedReceiver<FinalizedBlock>,
) {
    while let Some(f) = rx.recv().await {
        // Execute the finalized chain up to this digest. The returned height
        // is the height OF THIS DIGEST, so the certificate is attached to the
        // block it actually signs.
        let (height, timestamp_nanos) = match node.finalize(f.payload_digest).await {
            Some(v) => v,
            None => {
                tracing::debug!(
                    round = %f.round,
                    payload_digest = %hex::encode(f.payload_digest),
                    "Finalization not applied (already executed, or execution halted)"
                );
                continue;
            }
        };

        tracing::info!(
            height = height,
            round = %f.round,
            payload_digest = %hex::encode(f.payload_digest),
            cert_len = f.cert_bytes.len(),
            certificate = %hex::encode(&f.cert_bytes),
            "Block finalized with BLS threshold certificate (CONS-05)"
        );

        // CONS-05 + BLS light client: certificate, the exact signed Proposal
        // bytes (ops::verify_message::<MinSig>(group_pubkey, namespace,
        // proposal_bytes, certificate)) and the timestamp, in one commit.
        if f.cert_bytes.is_empty() {
            continue;
        }
        let mut app = app.write().await;
        match app.set_block_finality(height, f.cert_bytes, f.proposal_bytes, timestamp_nanos) {
            Ok(()) => tracing::info!(height, "Finality record stored (certificate, proposal, timestamp)"),
            Err(e) => tracing::error!(
                height,
                error = ?e,
                "Failed to store finality record — light client verification unavailable for this height"
            ),
        }
    }
    tracing::error!("Executor channel closed — no further blocks will be executed");
}

impl<S> Reporter for LayerReporter<S>
where
    S: commonware_cryptography::certificate::Scheme,
{
    type Activity = commonware_consensus::simplex::types::Activity<S, sha256::Digest>;

    async fn report(&mut self, activity: Self::Activity) {
        use commonware_codec::codec::Encode as _;
        use commonware_consensus::simplex::types::Activity;

        match &activity {
            Activity::Finalization(finalization) => {
                // CONS-05: Finalized block with BLS threshold certificate.
                // The certificate bytes are produced by the consensus engine after a quorum
                // of validators certify. They are NOT available at certify() time.
                let f = FinalizedBlock {
                    payload_digest: finalization.proposal.payload.0,
                    cert_bytes: finalization.certificate.encode().to_vec(),
                    proposal_bytes: finalization.proposal.encode().to_vec(),
                    round: format!("{:?}", finalization.proposal.round),
                };
                if self.exec_tx.send(f).is_err() {
                    tracing::error!("Executor task gone — finalization dropped");
                }
            }
            Activity::Notarization(notarization) => {
                tracing::debug!(
                    view = ?notarization.proposal.round,
                    "Block notarized"
                );
            }
            Activity::Nullification(nullification) => {
                tracing::debug!(
                    round = ?nullification.round,
                    "View nullified (skipped)"
                );
            }
            _ => {
                tracing::trace!("Consensus activity received");
            }
        }
    }
}

fn main() {
    // Parse CLI arguments or use env var for config path.
    let config_path = std::env::args()
        .skip(1)
        .find(|arg| !arg.starts_with('-'))
        .or_else(|| std::env::var("SLAY_CONFIG").ok())
        .unwrap_or_else(|| "config/node.toml".to_string());

    // Load node config from TOML.
    let config = match NodeConfig::from_file(&config_path) {
        Ok(cfg) => cfg,
        Err(e) => {
            eprintln!("Error: failed to load config from '{config_path}': {e}");
            eprintln!("Set SLAY_CONFIG or pass config path as first argument.");
            std::process::exit(1);
        }
    };

    // Init tracing with env-filter (respects RUST_LOG).
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    info!(
        chain_id = %config.chain_id,
        validator_index = config.validator_index,
        p2p_listen = %config.p2p_listen,
        grpc_listen = %config.grpc_listen,
        "slay3rd: starting Layer Commonware consensus node"
    );

    // Load BLS key material. If missing, exit with a clear error.
    // INVARIANT: Consensus MUST NOT start until DKG key material is validated.
    let km = match KeyMaterial::load(&config.bls_key_path) {
        Ok(km) => {
            info!(
                validator_index = km.validator_index,
                share_index = km.share_index,
                threshold = %format!("{}/{}", km.threshold_required, km.threshold_total),
                "BLS key material loaded"
            );
            km
        }
        Err(e) => {
            error!(
                path = %config.bls_key_path,
                error = %e,
                "Failed to load BLS key material — generate with tools/generate-testnet-keys"
            );
            std::process::exit(1);
        }
    };

    // Use commonware_runtime::tokio::Runner to provide the Context needed by Engine::new().
    // Runner::start() blocks until the future completes.
    //
    // IMPORTANT: Runner::default() stores the consensus journal under a RANDOM
    // temp dir in the container's writable layer — lost on --force-recreate,
    // which resets consensus to height 1 and desyncs it from persisted app
    // state (BadBlockHeight). Point storage_directory at the persistent
    // {data_dir}/consensus so a binary-swap upgrade resumes cleanly.
    let consensus_dir = config.consensus_storage_path();
    std::fs::create_dir_all(&consensus_dir).expect("Failed to create consensus directory");
    let runner_cfg = commonware_runtime::tokio::Config::new()
        .with_storage_directory(std::path::PathBuf::from(&consensus_dir));
    let runner = commonware_runtime::tokio::Runner::new(runner_cfg);
    runner.start(|context| async move {
        run_node(context, config, km).await
    });
}

/// Main async node logic. Receives a commonware_runtime::tokio::Context from the Runner.
async fn run_node(
    context: commonware_runtime::tokio::Context,
    config: NodeConfig,
    km: KeyMaterial,
) {
    // -----------------------------------------------------------------------
    // App initialization with feature-gated storage
    // -----------------------------------------------------------------------

    let wal_path = config.wal_path();
    let app_data_path = config.app_data_path();

    // Create data directories
    std::fs::create_dir_all(&wal_path).expect("Failed to create WAL directory");
    std::fs::create_dir_all(&app_data_path).expect("Failed to create app data directory");

    #[cfg(feature = "rocksdb")]
    let storage = RockStore::open(&app_data_path);
    #[cfg(not(feature = "rocksdb"))]
    let storage = MemoryStore::default();

    let logic = StateMachine::new(&AppConfig::new(&wal_path));
    let mut app = App::new(storage, logic);

    // Validator-local min gas price (mempool admission filter, CheckTx only).
    // e.g. "0.001ujclaw"; "0<denom>" disables the floor.
    match layer_app::MinGasPrice::parse(&config.min_gas_price) {
        Some(mgp) => {
            info!(min_gas_price = %config.min_gas_price, "Min gas price set");
            app.set_min_gas_price(Some(mgp));
        }
        None => {
            warn!(min_gas_price = %config.min_gas_price, "Invalid min_gas_price — fee floor disabled");
        }
    }

    // Attempt to load state; if none exists, initialize from genesis.
    use layer_app::AppLoadError;
    match app.load_from_storage() {
        Ok(()) => {
            info!("App loaded from existing storage");
        }
        Err(AppLoadError::NoStoredState) => {
            if let Some(ss) = &config.state_sync {
                // State-sync bootstrap: adopt a peer's snapshot — the only
                // trust anchor is the BLS-certified BlockPayload.state_root
                // (docs/STATE_SYNC.md §4). Failure is FATAL: falling back
                // to genesis would fork the node onto a divergent state.
                info!(peers = ?ss.peers, min_anchor_agree = ss.min_anchor_agree,
                    "No stored state — attempting state-sync");
                match slay3rd::state_sync::adopt_snapshot(
                    &mut app,
                    ss,
                    &config.chain_id,
                )
                .await
                {
                    Ok(h) => info!(height = h, "state-sync: snapshot adopted"),
                    Err(e) => {
                        error!(error = ?e, "state-sync failed — refusing genesis fallback");
                        return;
                    }
                }
            } else {
                info!("No stored state — initializing from genesis");
                let genesis = default_genesis();
                let app_state = match serde_json::to_vec(&genesis) {
                    Ok(b) => b,
                    Err(e) => {
                        error!(error = %e, "Failed to serialize genesis state");
                        return;
                    }
                };
                let init_req = layer_std::api::InitChainRequest {
                    time: cosmwasm_std::Timestamp::from_nanos(1_673_194_026_078_305_426),
                    chain_id: config.chain_id.clone(),
                    consensus_params: Default::default(),
                    validators: vec![],
                    app_state: cosmwasm_std::Binary::from(app_state),
                    initial_height: 1,
                };
                if let Err(e) = app.init(init_req) {
                    error!(error = ?e, "Failed to initialize App from genesis");
                    return;
                }
            }
        }
        Err(e) => {
            error!(error = ?e, "State corruption — cannot continue");
            return;
        }
    }

    // -----------------------------------------------------------------------
    // LayerNode + LayerRelay (SHARED pending_payloads)
    // -----------------------------------------------------------------------

    let mempool = Arc::new(Mutex::new(Mempool::new(config.mempool_max_pending)));

    // Resume block production at the app's persisted height. LayerNode tracks
    // current_height in memory and proposes current_height+1; passing 0 always
    // restarts at height 1, which desyncs from persisted app state on
    // restart/recreate (BadBlockHeight). After genesis init info().height==0
    // (next block = 1); after load_from_storage it's the last committed height.
    let resume_height = app.info().map(|b| b.height).unwrap_or(0);
    let app_arc = Arc::new(RwLock::new(app));

    #[cfg(feature = "rocksdb")]
    let layer_node = LayerNode::<RockStore, ed25519::PublicKey>::new(
        app_arc.clone(),
        mempool.clone(),
        resume_height,
    );
    #[cfg(not(feature = "rocksdb"))]
    let layer_node = LayerNode::<MemoryStore, ed25519::PublicKey>::new(
        app_arc.clone(),
        mempool.clone(),
        resume_height,
    );

    // Durable payload store: certified-but-unexecuted payloads survive restart
    // and are re-broadcast; executed payloads are retained to serve peers.
    let payload_store = match slay3rd::payload_store::PayloadStore::open(format!("{}/payloads", config.data_dir)) {
        Ok(s) => s,
        Err(e) => {
            error!(error = %e, "Failed to open payload store");
            return;
        }
    };
    let (layer_node, recovered_payloads) = layer_node.with_payload_store(payload_store).await;
    let layer_node = layer_node.with_fault_inject(config.fault_inject.clone());
    if let Some(mode) = &config.fault_inject {
        tracing::warn!(
            mode = %mode,
            "FAULT INJECTION ENABLED — chaos testing only, never enable on a real validator"
        );
    }
    let (payload_fetch_tx, payload_fetch_rx) = tokio::sync::mpsc::unbounded_channel::<FetchRequest>();
    layer_node.set_fetch_sender(payload_fetch_tx);
    info!(recovered = recovered_payloads.len(), "Payload store opened");
    let p2p_node = layer_node.clone();

    let tx_index = layer_node.tx_index();

    // Create an unbounded channel to forward payload bytes from the relay's broadcast()
    // to the background P2P sender task. The relay serializes payloads and sends them here;
    // the background task broadcasts them to all peers via the authenticated P2P channel.
    let (payload_broadcast_tx, payload_broadcast_rx) =
        tokio::sync::mpsc::unbounded_channel::<bytes::Bytes>();

    // Tx gossip: BroadcastTx-accepted raw tx bytes are pushed here by the
    // gRPC service and forwarded to all validator peers over P2P channel 4,
    // so a tx submitted to a non-leader does not wait for that node's own
    // proposal slot (M1).
    let (tx_gossip_tx, tx_gossip_rx) =
        tokio::sync::mpsc::unbounded_channel::<bytes::Bytes>();

    // CRITICAL: The relay MUST receive the SAME pending_payloads Arc from LayerNode.
    // This is what allows non-proposer validators to find payloads in verify().
    let relay = LayerRelay::new(layer_node.pending_payloads(), Some(payload_broadcast_tx.clone()));
    // CONS-05: Reporter holds the app Arc so it can persist BLS certificates
    // via set_block_certificate() when the Finalization activity fires.
    let (exec_tx, exec_rx) = tokio::sync::mpsc::unbounded_channel::<FinalizedBlock>();
    tokio::spawn(run_executor(app_arc.clone(), layer_node.clone(), exec_rx));
    // The LayerReporter is constructed inside the consensus-scheme branch
    // below — its certificate type differs between classical and hybrid mode.

    info!("LayerNode and LayerRelay created (shared pending_payloads)");

    // -----------------------------------------------------------------------
    // BLS12-381 threshold scheme from DKG key material
    // -----------------------------------------------------------------------

    // Decode our own Ed25519 public key first (needed to find our sorted position).
    // This is decoded from km.ed25519_public_hex — the authoritative source for our key.
    let our_ed25519_pk_early = match hex::decode(&km.ed25519_public_hex) {
        Ok(bytes) => match ed25519::PublicKey::decode(bytes::Bytes::from(bytes)) {
            Ok(pk) => pk,
            Err(e) => {
                error!(error = %e, "Failed to decode our Ed25519 public key");
                return;
            }
        },
        Err(e) => {
            error!(error = %e, "Invalid hex in ed25519_public_hex");
            return;
        }
    };

    // Decode all validator Ed25519 public keys.
    let mut participant_keys: Vec<ed25519::PublicKey> = Vec::new();
    for hex_key in &km.validator_public_keys {
        match hex::decode(hex_key) {
            Ok(key_bytes) => {
                match ed25519::PublicKey::decode(bytes::Bytes::from(key_bytes)) {
                    Ok(pk) => participant_keys.push(pk),
                    Err(e) => {
                        error!(error = %e, "Failed to decode validator Ed25519 public key");
                        return;
                    }
                }
            }
            Err(e) => {
                error!(error = %e, "Invalid hex in validator_public_keys");
                return;
            }
        }
    }

    // Sort participant_keys into binary order — required by commonware_utils::ordered::Set.
    // The keygen tool stores keys in validator_index order, NOT sorted binary order.
    // The sorted position of our key is what determines which BLS share we hold.
    //
    // Hybrid mode: validator_mayo_public_keys is in the same validator_index
    // order, so we sort (ed25519, mayo) pairs to keep the MAYO identity table
    // aligned with the sorted participant set (PQ_PROTOCOL_AUTH.md §3).
    let mayo_pks: Option<Vec<Vec<u8>>> = if config.hybrid_consensus {
        let mayo_hexes = match &km.validator_mayo_public_keys {
            Some(l) if l.len() == participant_keys.len() => l.clone(),
            Some(l) => {
                error!(
                    expected = participant_keys.len(),
                    got = l.len(),
                    "validator_mayo_public_keys length mismatch"
                );
                return;
            }
            None => {
                error!("hybrid_consensus enabled but key file lacks validator_mayo_public_keys");
                return;
            }
        };
        let mut pairs: Vec<(ed25519::PublicKey, Vec<u8>)> =
            Vec::with_capacity(mayo_hexes.len());
        for (pk, mh) in participant_keys.iter().cloned().zip(mayo_hexes.iter()) {
            match hex::decode(mh) {
                Ok(b) if b.len() == junoclaw_mayo_verify::Mayo2::PK_BYTES => pairs.push((pk, b)),
                Ok(b) => {
                    error!(len = b.len(), "MAYO public key wrong size — expected MAYO2");
                    return;
                }
                Err(e) => {
                    error!(error = %e, "Invalid hex in validator_mayo_public_keys");
                    return;
                }
            }
        }
        pairs.sort_by(|a, b| {
            let a_bytes: &[u8] = a.0.as_ref();
            let b_bytes: &[u8] = b.0.as_ref();
            a_bytes.cmp(b_bytes)
        });
        participant_keys = pairs.iter().map(|(pk, _)| pk.clone()).collect();
        Some(pairs.into_iter().map(|(_, m)| m).collect())
    } else {
        participant_keys.sort_by(|a, b| {
            let a_bytes: &[u8] = a.as_ref();
            let b_bytes: &[u8] = b.as_ref();
            a_bytes.cmp(b_bytes)
        });
        None
    };

    // Find our sorted position — this is the index into the BLS shares array.
    // shares[0] was assigned to the validator whose sorted position is 0, etc.
    // Using validator_index here would be WRONG if the sorted order differs from
    // the key generation order (which it does when keys are not pre-sorted).
    let our_sorted_position = match participant_keys
        .iter()
        .position(|pk| pk.as_ref() == our_ed25519_pk_early.as_ref())
    {
        Some(pos) => pos,
        None => {
            error!("Our Ed25519 key is not present in the validator_public_keys list");
            return;
        }
    };

    info!(
        validator_index = km.validator_index,
        our_sorted_position = our_sorted_position,
        "Ed25519 sorted position determined for BLS share selection"
    );

    let participants = match commonware_utils::ordered::Set::try_from(participant_keys.as_slice()) {
        Ok(s) => s,
        Err(e) => {
            error!(error = %e, "Failed to build participant set (keys may be unordered or duplicate)");
            return;
        }
    };

    // Reconstruct the BLS sharing polynomial and our share.
    //
    // Phase A ceremony key files carry serialized `Sharing` + `Share`
    // (sharing_hex/share_hex, written by `generate-testnet-keys finalize`) —
    // load them directly. Legacy devnet key files lack these fields, so we
    // reproduce the keygen tool's deterministic deal (seeded RNG) and pick
    // our share by sorted Ed25519 position.
    let n = match NonZeroU32::new(km.threshold_total) {
        Some(n) => n,
        None => {
            error!("threshold_total must be > 0");
            return;
        }
    };

    let (sharing, our_share) = if let (Some(sharing_hex), Some(share_hex)) =
        (&km.sharing_hex, &km.share_hex)
    {
        let sharing_bytes = match hex::decode(sharing_hex) {
            Ok(b) => b,
            Err(e) => {
                error!(error = %e, "Invalid hex in sharing_hex");
                return;
            }
        };
        let share_bytes = match hex::decode(share_hex) {
            Ok(b) => b,
            Err(e) => {
                error!(error = %e, "Invalid hex in share_hex");
                return;
            }
        };
        let sharing = match Sharing::<MinSig>::read_cfg(
            &mut &sharing_bytes[..],
            &(n, ModeVersion::v0()),
        ) {
            Ok(s) => s,
            Err(e) => {
                error!(error = %e, "Failed to decode sharing from keys.json");
                return;
            }
        };
        let share = match Share::read_cfg(&mut &share_bytes[..], &()) {
            Ok(s) => s,
            Err(e) => {
                error!(error = %e, "Failed to decode share from keys.json");
                return;
            }
        };
        info!("BLS share loaded from keys.json (ceremony key material)");
        (sharing, share)
    } else {
        // Use the same seeded RNG as the keygen tool to reproduce the same DKG output.
        let mut rng = ChaCha8Rng::seed_from_u64(0);
        // Skip Ed25519 key generation (same as keygen tool does first) to advance RNG state.
        for _ in 0..km.threshold_total {
            let _ = ed25519::PrivateKey::random(&mut rng);
        }
        let (sharing, shares) = deal_anonymous::<MinSig, N3f1>(&mut rng, Mode::NonZeroCounter, n);

        if our_sorted_position >= shares.len() {
            error!(
                our_sorted_position = our_sorted_position,
                total = shares.len(),
                "sorted position out of range — BLS share count mismatch"
            );
            return;
        }
        // Use sorted position (not validator_index) to select the correct BLS share.
        // shares[i] was assigned to the validator whose sorted Ed25519 key position is i.
        (sharing, shares[our_sorted_position].clone())
    };

    // Create the BLS threshold signing Scheme.
    let bls_scheme = match BlsScheme::<ed25519::PublicKey, MinSig>::signer(
        NAMESPACE,
        participants.clone(),
        sharing,
        our_share,
    ) {
        Some(s) => s,
        None => {
            error!("BLS scheme creation failed — share does not match polynomial");
            return;
        }
    };

    info!(
        validator_index = km.validator_index,
        threshold = %format!("{}/{}", km.threshold_required, km.threshold_total),
        "BLS12-381 threshold signing scheme initialized"
    );

    // -----------------------------------------------------------------------
    // gRPC server with Cosmos SDK query dispatch
    //
    // Serves two tonic services:
    //   1. cosmos.tx.v1beta1.Service (BroadcastTx + stub methods)
    //   2. layer.sync.v1.Query (state sync streaming)
    //
    // Cosmos SDK query paths (/cosmos.bank.*, /cosmos.auth.*, /cosmwasm.wasm.*)
    // are dispatched via an axum fallback handler (cosmos_query_fallback) that
    // calls handle_cosmos_query() and returns properly gRPC-framed responses.
    //
    // Architecture:
    //   1. Build an axum::Router with cosmos_query_fallback as the fallback handler
    //   2. Convert it to tonic::service::Routes via From<axum::Router>
    //   3. Start the tonic server via GrpcServer::builder().add_routes(routes)
    //   4. Chain add_service() for the tonic services — these take priority over the fallback
    // -----------------------------------------------------------------------
    {
        let grpc_addr: SocketAddr = config.grpc_listen.parse()
            .expect("Invalid grpc_listen address in config");

        let grpc_svc = LayerGrpcService {
            app: app_arc.clone(),
            mempool: mempool.clone(),
            chain_id: config.chain_id.clone(),
            tx_index: tx_index.clone(),
            snapshot_cache: std::sync::Arc::new(tokio::sync::Mutex::new(None)),
            tx_gossip: Some(tx_gossip_tx),
        };

        // Cosmos query dispatch state for the axum fallback handler.
        // The fallback intercepts /cosmos.bank.*, /cosmos.auth.*, /cosmwasm.wasm.* paths
        // and dispatches them to handle_cosmos_query() in grpc.rs.
        #[cfg(feature = "rocksdb")]
        let cosmos_state = slay3rd::grpc::CosmosQueryState::<layer_storage::RockStore> {
            app: app_arc.clone(),
            chain_id: config.chain_id.clone(),
        };
        #[cfg(not(feature = "rocksdb"))]
        let cosmos_state = slay3rd::grpc::CosmosQueryState::<layer_storage::MemoryStore> {
            app: app_arc.clone(),
            chain_id: config.chain_id.clone(),
        };

        tokio::spawn(async move {
            info!(addr = %grpc_addr, "Starting gRPC server with Cosmos query dispatch");

            // Build an axum Router with the Cosmos query fallback service.
            // This catches all paths not handled by the tonic services (BroadcastTx, SyncQuery).
            // Uses fallback_service (tower Service) to avoid axum Handler version conflicts.
            let cosmos_router = slay3rd::grpc::cosmos_query_router(cosmos_state);

            // Convert the axum router to tonic Routes, then add tonic services on top.
            // The tonic services (registered via route_service) take priority over the fallback.
            let cosmos_routes = tonic::service::Routes::from(cosmos_router);

            let reflection = tonic_reflection::server::Builder::configure()
                .register_encoded_file_descriptor_set(layer_proto::FILE_DESCRIPTOR_SET)
                .build_v1()
                .expect("gRPC reflection build failed");

            GrpcServer::builder()
                .add_routes(cosmos_routes)
                .add_service(reflection)
                .add_service(
                    layer_proto::cosmos::tx::v1beta1::service_server::ServiceServer::new(
                        grpc_svc.clone(),
                    )
                    .max_decoding_message_size(10 * 1024 * 1024)
                    .max_encoding_message_size(10 * 1024 * 1024),
                )
                .add_service(
                    layer_proto::layer::sync::v1::query_server::QueryServer::new(grpc_svc.clone()),
                )
                .add_service(
                    layer_proto::layer::lightclient::v1::query_server::QueryServer::new(
                        grpc_svc.clone(),
                    ),
                )
                .add_service(
                    layer_proto::layer::statesync::v1::query_server::QueryServer::new(grpc_svc)
                        // snapshot chunks are ~8 MiB each — lift the 4 MiB
                        // default so chunk responses aren't truncated
                        .max_encoding_message_size(12 * 1024 * 1024),
                )
                .serve(grpc_addr)
                .await
                .expect("gRPC server failed");
        });

        info!(grpc_listen = %config.grpc_listen, "gRPC server spawned with Cosmos query dispatch");
    }

    // -----------------------------------------------------------------------
    // P2P network (authenticated::lookup — real cross-process TLS + Ed25519)
    // -----------------------------------------------------------------------

    // Decode our Ed25519 private key for P2P identity
    let ed25519_priv_bytes = hex::decode(&km.ed25519_private_hex)
        .expect("Invalid hex in ed25519_private_hex");
    let ed25519_private_key = ed25519::PrivateKey::decode(
        bytes::Bytes::from(ed25519_priv_bytes)
    ).expect("Invalid ed25519 private key bytes");

    // Use the key decoded from km.ed25519_public_hex — already decoded early for sorted-position lookup.
    let our_ed25519_pk = our_ed25519_pk_early.clone();
    let p2p_listen: SocketAddr = config.p2p_listen.parse()
        .expect("Invalid p2p_listen address in config");

    // Config::local() minimizes handshake latency for localhost testing
    let p2p_cfg = P2pConfig::local(
        ed25519_private_key.clone(),
        b"slay3r-p2p-v1",
        p2p_listen,
        10 * 1024 * 1024,  // 10MB max message size (accommodates large store-code txs)
    );

    let p2p_ctx = context.with_label("p2p");
    let (mut network, mut oracle) = Network::new(p2p_ctx, p2p_cfg);

    // Register channels BEFORE start()
    let quota = commonware_runtime::Quota::per_second(NonZeroU32::MAX);
    let (vote_sender, vote_receiver) = network.register(0, quota, 128);
    let (cert_sender, cert_receiver) = network.register(1, quota, 128);
    let (res_sender, res_receiver) = network.register(2, quota, 128);
    // Channel 3: block payload relay (broadcast to peers, receive from peers)
    let (payload_p2p_sender, mut payload_p2p_receiver) = network.register(3, quota, 128);
    // Channel 4: tx gossip (raw tx bytes, forwarded from BroadcastTx)
    let (tx_p2p_sender, mut tx_p2p_receiver) = network.register(4, quota, 128);

    // Build peer map: all validators including self
    // Address implements From<SocketAddr>; Map is built via try_into() from array/slice.
    // We need to add entries dynamically so we collect into a Vec then try_into.
    let mut peer_entries: Vec<(ed25519::PublicKey, P2pAddress)> = Vec::new();

    // Add self first
    peer_entries.push((our_ed25519_pk.clone(), P2pAddress::from(p2p_listen)));

    // Add peers from config
    for peer in &config.peers {
        let addr: SocketAddr = peer.address.parse()
            .unwrap_or_else(|_| panic!("Invalid peer address: {}", peer.address));
        let pk_bytes = hex::decode(&peer.public_key)
            .unwrap_or_else(|_| panic!("Invalid peer public_key hex: {}", peer.public_key));
        let pk = ed25519::PublicKey::decode(bytes::Bytes::from(pk_bytes))
            .expect("Invalid ed25519 peer public key");
        peer_entries.push((pk, P2pAddress::from(addr)));
    }

    // Build the ordered Map from the entries vec.
    // Map::try_from requires entries to be in sorted order by key.
    // If keys are not sorted, sort them first.
    peer_entries.sort_by(|(a, _), (b, _)| {
        let a_bytes: &[u8] = a.as_ref();
        let b_bytes: &[u8] = b.as_ref();
        a_bytes.cmp(b_bytes)
    });

    // Deduplicate in case of duplicates (e.g., self appears in peers config)
    peer_entries.dedup_by(|(a, _), (b, _)| {
        let a_bytes: &[u8] = a.as_ref();
        let b_bytes: &[u8] = b.as_ref();
        a_bytes == b_bytes
    });

    let peer_map = Map::try_from(peer_entries.as_slice())
        .expect("Failed to build peer map — keys may be unordered or duplicate");
    oracle.track(0, peer_map).await;

    // Start AFTER register() calls
    network.start();

    info!("Authenticated P2P network initialized ({} peers)", config.peers.len() + 1);

    // -----------------------------------------------------------------------
    // Payload relay P2P tasks
    //
    // Task A (broadcast): reads serialized payload bytes from payload_broadcast_rx
    //   (written by LayerRelay::broadcast() on the proposer) and sends them to
    //   all peers via the authenticated P2P channel 3.
    //
    // Task B (receive): reads incoming payload bytes from the P2P channel 3 receiver
    //   and inserts deserialized BlockPayloads into the shared pending_payloads map,
    //   enabling non-proposer validators to succeed in verify().
    // -----------------------------------------------------------------------

    // Task A: forward payload bytes from relay to P2P (proposer path)
    {
        let mut sender = payload_p2p_sender.clone();
        let mut rx = payload_broadcast_rx;
        tokio::spawn(async move {
            while let Some(payload_bytes) = rx.recv().await {
                let psize = payload_bytes.len();
                let mut framed = Vec::with_capacity(psize + 1);
                framed.push(PAYLOAD_MSG_PUSH);
                framed.extend_from_slice(&payload_bytes);
                let payload_bytes = bytes::Bytes::from(framed);
                match P2pSender::send(&mut sender, Recipients::All, payload_bytes, true).await {
                    Ok(sent_to) => {
                        tracing::info!(
                            peers = sent_to.len(),
                            payload_bytes = psize,
                            "Payload relay: broadcast to {} peers via P2P",
                            sent_to.len()
                        );
                    }
                    Err(e) => {
                        tracing::warn!(error = ?e, payload_bytes = psize, "Payload relay: P2P broadcast failed");
                    }
                }
            }
            tracing::info!("Payload relay broadcast task exited");
        });
    }

    // Re-broadcast payloads recovered from disk (certified but not executed
    // before restart) once peers have had time to connect.
    {
        let tx = payload_broadcast_tx;
        tokio::spawn(async move {
            tokio::time::sleep(Duration::from_secs(5)).await;
            for p in recovered_payloads {
                let _ = tx.send(bytes::Bytes::from(p.to_bytes()));
            }
        });
    }

    // Tx gossip egress: drain the gRPC-forwarded queue onto P2P channel 4.
    {
        let mut sender = tx_p2p_sender.clone();
        let mut rx = tx_gossip_rx;
        tokio::spawn(async move {
            while let Some(tx_bytes) = rx.recv().await {
                if let Err(e) =
                    P2pSender::send(&mut sender, Recipients::All, tx_bytes, true).await
                {
                    tracing::warn!(error = ?e, "Tx gossip: send failed");
                }
            }
        });
    }

    // Tx gossip ingress: validate + admit peer-forwarded raw tx bytes.
    // check_tx gates admission (same rules as BroadcastTx); mempool dedupe
    // makes repeat delivery idempotent; invalid bytes are dropped.
    {
        let app = app_arc.clone();
        let mempool = mempool.clone();
        let chain_id = config.chain_id.clone();
        tokio::spawn(async move {
            loop {
                match tx_p2p_receiver.recv().await {
                    Ok((_peer, message)) => {
                        let raw: bytes::Bytes = message.into();
                        let Ok(tx) = layer_cosmos::parse_cosmos_tx(raw.clone(), &chain_id)
                        else {
                            continue;
                        };
                        // Admission metadata — captured before check_tx
                        // consumes the tx (M4 ordering, M7 caps).
                        let layer_std::Tx::Signed(ref signed) = tx;
                        let meta = slay3rd::mempool::TxMeta {
                            sender: signed.signer.to_string(),
                            sequence: signed.signing_info.sequence,
                            store_code: signed.msgs.iter().any(|m| {
                                matches!(
                                    m,
                                    layer_std::Msg::Wasm(
                                        layer_std::WasmMsg::StoreCode { .. }
                                    )
                                )
                            }),
                        };
                        let ok = {
                            let app = app.read().await;
                            app.info().is_some() && app.check_tx(tx).result.is_ok()
                        };
                        if !ok {
                            continue;
                        }
                        let _ = mempool
                            .lock()
                            .await
                            .submit_checked(raw, Some(meta));
                    }
                    Err(_) => break,
                }
            }
        });
    }

    // Task C: ask peers for payloads this node is missing (certify/finalize
    // digest requests, plus bulk height-range backfill requests).
    {
        let mut sender = payload_p2p_sender.clone();
        let mut rx = payload_fetch_rx;
        tokio::spawn(async move {
            while let Some(req) = rx.recv().await {
                let msg = match req {
                    FetchRequest::Digest(digest) => {
                        let mut msg = Vec::with_capacity(33);
                        msg.push(PAYLOAD_MSG_REQUEST);
                        msg.extend_from_slice(&digest);
                        msg
                    }
                    FetchRequest::HeightRange { start, count } => {
                        let mut msg = Vec::with_capacity(11);
                        msg.push(PAYLOAD_MSG_REQUEST_RANGE);
                        msg.extend_from_slice(&start.to_be_bytes());
                        msg.extend_from_slice(&count.to_be_bytes());
                        msg
                    }
                };
                if let Err(e) = P2pSender::send(&mut sender, Recipients::All, bytes::Bytes::from(msg), true).await {
                    tracing::warn!(error = ?e, "Payload fetch: request send failed");
                }
            }
        });
    }

    // Task D: bulk backfill — every BACKFILL_TICK, request every missing
    // height between the executed tip and the highest observed payload
    // height. Turns a long outage into ~parallel fetches instead of the
    // finalize() digest walk's one-RTT-per-block crawl.
    const BACKFILL_TICK: Duration = Duration::from_millis(250);
    {
        let node = p2p_node.clone();
        tokio::spawn(async move {
            loop {
                tokio::time::sleep(BACKFILL_TICK).await;
                node.backfill_tick().await;
            }
        });
    }

    // Task B: receive payload pushes / requests from P2P (non-proposer path)
    {
        let node = p2p_node;
        let mut reply_sender = payload_p2p_sender.clone();
        tokio::spawn(async move {
            loop {
                match payload_p2p_receiver.recv().await {
                    Ok((sender_pk, message)) => {
                        let raw: &[u8] = message.as_ref();
                        let (tag, payload_bytes) = match raw.split_first() {
                            Some((tag, body)) => (*tag, body),
                            None => continue,
                        };
                        if tag == PAYLOAD_MSG_REQUEST {
                            let Ok(digest) = <[u8; 32]>::try_from(payload_bytes) else {
                                tracing::warn!("Payload fetch: malformed request");
                                continue;
                            };
                            if let Some(p) = node.lookup_payload(&digest).await {
                                let mut msg = vec![PAYLOAD_MSG_PUSH];
                                msg.extend_from_slice(&p.to_bytes());
                                if let Err(e) = P2pSender::send(
                                    &mut reply_sender,
                                    Recipients::One(sender_pk),
                                    bytes::Bytes::from(msg),
                                    true,
                                ).await {
                                    tracing::warn!(error = ?e, "Payload fetch: reply send failed");
                                }
                            }
                            continue;
                        }
                        if tag == PAYLOAD_MSG_REQUEST_RANGE {
                            // Body: u64be start + u16be count. Serve each
                            // height we hold as a separate PUSH frame, capped
                            // at BACKFILL_BATCH_SIZE to bound reply fan-out.
                            if payload_bytes.len() != 10 {
                                tracing::warn!("Payload fetch: malformed range request");
                                continue;
                            }
                            let start = u64::from_be_bytes(payload_bytes[..8].try_into().unwrap());
                            let count = u16::from_be_bytes(payload_bytes[8..10].try_into().unwrap())
                                as u64;
                            let count = count.min(slay3rd::node::BACKFILL_BATCH_SIZE);
                            for h in start..start + count {
                                let Some(p) = node.payload_by_height(h).await else {
                                    continue;
                                };
                                let mut msg = vec![PAYLOAD_MSG_PUSH];
                                msg.extend_from_slice(&p.to_bytes());
                                if let Err(e) = P2pSender::send(
                                    &mut reply_sender,
                                    Recipients::One(sender_pk.clone()),
                                    bytes::Bytes::from(msg),
                                    true,
                                ).await {
                                    tracing::warn!(error = ?e, "Payload backfill: reply send failed");
                                    break;
                                }
                            }
                            continue;
                        }
                        if tag != PAYLOAD_MSG_PUSH {
                            tracing::warn!(tag, "Payload relay: unknown message tag");
                            continue;
                        }
                        let psize = payload_bytes.len();
                        match slay3rd::block::BlockPayload::from_bytes(payload_bytes) {
                            Ok(payload) => {
                                let digest = payload.digest();
                                let height = payload.height;
                                match node.accept_peer_payload(payload).await {
                                    Ok(true) => tracing::info!(
                                        height,
                                        digest = %hex::encode(digest),
                                        payload_bytes = psize,
                                        "Payload relay: received from peer, inserted into pending_payloads"
                                    ),
                                    Ok(false) => {}
                                    Err(reason) => tracing::debug!(
                                        height,
                                        digest = %hex::encode(digest),
                                        reason,
                                        "Payload relay: peer payload rejected"
                                    ),
                                }
                            }
                            Err(e) => {
                                tracing::warn!(error = %e, payload_bytes = psize, "Payload relay: received malformed payload bytes");
                            }
                        }
                    }
                    Err(e) => {
                        tracing::info!(error = ?e, "Payload relay receive task: channel closed");
                        break;
                    }
                }
            }
            tracing::info!("Payload relay receive task exited");
        });
    }

    // -----------------------------------------------------------------------
    // Simplex consensus Engine
    // -----------------------------------------------------------------------

    let leader_timeout = Duration::from_millis(config.leader_timeout_ms);
    let cert_timeout = Duration::from_millis(config.certification_timeout_ms);
    let timeout_retry = Duration::from_millis((config.leader_timeout_ms / 2).max(100));

    // The lookup Oracle implements Blocker directly (no oracle.control(pk) needed).
    //
    // Phase 2a (docs/PQ_PROTOCOL_AUTH.md): with `hybrid_consensus = true` the
    // engine runs HybridScheme — every vote carries BLS + MAYO2 and every
    // certificate requires both halves. Otherwise the classical BLS-only
    // scheme runs unchanged. The branch bodies are identical except for the
    // scheme/reporter types, which are fixed at compile time.
    if config.hybrid_consensus {
        let Some(mayo_pks) = mayo_pks else {
            error!("hybrid_consensus enabled but MAYO identity table was not built");
            return;
        };

        // Only MAYO2 is supported: fixed 186-byte signatures are what allow
        // HybridSignature to satisfy the CodecFixed bound.
        match km.mayo_variant.as_deref() {
            Some("mayo2") | Some("MAYO2") => {}
            other => {
                error!(variant = ?other, "Unsupported mayo_variant — only \"mayo2\" is supported");
                return;
            }
        }

        let mayo_seed = match &km.mayo_private_hex {
            Some(h) => match hex::decode(h) {
                Ok(b) => b,
                Err(e) => {
                    error!(error = %e, "Invalid hex in mayo_private_hex");
                    return;
                }
            },
            None => {
                error!("hybrid_consensus requires mayo_private_hex in the key file");
                return;
            }
        };

        // Sanity: our declared MAYO public key must sit at our sorted
        // participant position — catches identity-table misalignment at
        // startup instead of producing votes that never verify.
        if let Some(pk_hex) = &km.mayo_public_hex {
            match hex::decode(pk_hex) {
                Ok(pk) if pk == mayo_pks[our_sorted_position] => {}
                Ok(_) => {
                    error!(
                        "mayo_public_hex does not match validator_mayo_public_keys at our sorted position"
                    );
                    return;
                }
                Err(e) => {
                    error!(error = %e, "Invalid hex in mayo_public_hex");
                    return;
                }
            }
        }

        // pq_quorum == BLS threshold_required: the certificate needs the same
        // quorum of valid MAYO signatures as the classical threshold.
        let scheme = match HybridScheme::new(
            bls_scheme,
            NAMESPACE,
            mayo_pks,
            Some(mayo_seed),
            km.threshold_required as usize,
        ) {
            Some(s) => s,
            None => {
                error!("Hybrid scheme creation failed — MAYO table/quorum mismatch");
                return;
            }
        };
        info!("Hybrid BLS+MAYO2 consensus scheme initialized (PQ_PROTOCOL_AUTH Phase 2a)");

        let reporter = LayerReporter::<HybridScheme> {
            exec_tx,
            _scheme: PhantomData,
        };
        let consensus_cfg = SimplexConfig {
            scheme,
            elector: RoundRobin::<commonware_cryptography::Sha256>::default(),
            blocker: oracle,
            automaton: layer_node,
            relay,
            reporter,
            strategy: Sequential,
            partition: format!("slay3r-{}", config.chain_id),
            mailbox_size: 1024,
            epoch: CONSENSUS_EPOCH,
            replay_buffer: NZUsize!(1024 * 1024),
            write_buffer: NZUsize!(1024 * 1024),
            page_cache: CacheRef::from_pooler(&context, PAGE_SIZE, PAGE_CACHE_SIZE),
            leader_timeout,
            certification_timeout: cert_timeout,
            timeout_retry,
            activity_timeout: commonware_consensus::types::ViewDelta::new(10),
            skip_timeout: commonware_consensus::types::ViewDelta::new(5),
            fetch_timeout: Duration::from_secs(5),
            fetch_concurrent: 4,
        };

        consensus_cfg.assert();

        let consensus_ctx = context.with_label("consensus");
        let engine = Engine::new(consensus_ctx, consensus_cfg);
        info!("Starting simplex consensus engine (epoch=0, hybrid BLS+MAYO2)...");

        let _engine_handle = engine.start(
            (vote_sender, vote_receiver),
            (cert_sender, cert_receiver),
            (res_sender, res_receiver),
        );
    } else {
        let reporter = LayerReporter::<BlsScheme<ed25519::PublicKey, MinSig>> {
            exec_tx,
            _scheme: PhantomData,
        };
        let consensus_cfg = SimplexConfig {
            scheme: bls_scheme,
            elector: RoundRobin::<commonware_cryptography::Sha256>::default(),
            blocker: oracle,
            automaton: layer_node,
            relay,
            reporter,
            strategy: Sequential,
            partition: format!("slay3r-{}", config.chain_id),
            mailbox_size: 1024,
            epoch: CONSENSUS_EPOCH,
            replay_buffer: NZUsize!(1024 * 1024),
            write_buffer: NZUsize!(1024 * 1024),
            page_cache: CacheRef::from_pooler(&context, PAGE_SIZE, PAGE_CACHE_SIZE),
            leader_timeout,
            certification_timeout: cert_timeout,
            timeout_retry,
            activity_timeout: commonware_consensus::types::ViewDelta::new(10),
            skip_timeout: commonware_consensus::types::ViewDelta::new(5),
            fetch_timeout: Duration::from_secs(5),
            fetch_concurrent: 4,
        };

        consensus_cfg.assert();

        let consensus_ctx = context.with_label("consensus");
        let engine = Engine::new(consensus_ctx, consensus_cfg);
        info!("Starting simplex consensus engine (epoch=0)...");

        // Start engine with the three P2P channel pairs.
        let _engine_handle = engine.start(
            (vote_sender, vote_receiver),
            (cert_sender, cert_receiver),
            (res_sender, res_receiver),
        );
    }

    info!(
        grpc_listen = %config.grpc_listen,
        "Consensus engine started with authenticated P2P and gRPC server."
    );

    // Wait for shutdown signal (Ctrl+C).
    match tokio::signal::ctrl_c().await {
        Ok(()) => info!("Shutdown signal received — stopping slay3rd"),
        Err(e) => warn!(error = %e, "Error waiting for shutdown signal"),
    }
}

/// Default genesis state for testnet bootstrapping.
///
/// Includes a pre-funded deployer account for the tx-sender tool.
/// The deployer's secp256k1 private key is derived deterministically:
///   SHA256("junoclaw-deployer-v1")[0..32] (32 bytes)
/// The corresponding bech32 address is computed from the public key.
///
/// The tx-sender tool uses the same derivation to sign transactions.
fn default_genesis() -> GenesisState {
    use sha2::{Digest, Sha256};

    // Deterministic deployer key — same seed used by tools/tx-sender
    let seed = Sha256::digest(b"junoclaw-deployer-v1");
    let deployer_key = cosmrs::crypto::secp256k1::SigningKey::from_slice(&seed[..32])
        .expect("valid secp256k1 key from SHA256 seed");
    let deployer_addr = deployer_key
        .public_key()
        .account_id(layer_std::BECH32_PREFIX)
        .expect("valid bech32 address")
        .to_string();

    GenesisState {
        bank: vec![BankAccount {
            address: deployer_addr,
            balance: vec![cosmwasm_std::coin(1_000_000_000_000, "ujclaw")],
        }],
        wasm: WasmParams {
            gov_account: "juno1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmdyychx".to_string(),
        },
    }
}
