//! slay3rd — Layer Commonware consensus node entry point.
//!
//! This binary drives the Layer state machine through Commonware simplex consensus
//! with BLS12-381 threshold signatures (via the `bls12381_threshold::standard` scheme).
//!
//! # Startup sequence
//!
//! 1. Parse config (TOML file from `SLAY_CONFIG` env var or first CLI arg)
//! 2. Init tracing
//! 3. Load BLS key material (JSON from `config.bls_key_path`)
//! 4. Initialize storage (RocksDB with `rocksdb` feature, MemoryStore otherwise)
//! 5. Initialize App from genesis or load existing state
//! 6. Create Mempool and LayerNode (consensus bridge)
//! 7. Create LayerRelay (with SHARED pending_payloads from LayerNode)
//! 8. Create logging Reporter
//! 9. Spawn gRPC server with Cosmos SDK query dispatch
//! 10. Build authenticated P2P network (real cross-process TLS + Ed25519)
//! 11. Build simplex Engine config (BLS threshold scheme, round-robin elector)
//! 12. Spawn consensus engine via commonware_runtime::tokio::Runner
//!
//! # Key material
//!
//! Generated by `tools/generate-testnet-keys`. The JSON file contains:
//! - `bls_private_hex`: BLS secret share
//! - `threshold_public_key_hex`: group threshold public key
//! - `ed25519_public_hex`: this node's Ed25519 identity public key
//! - `ed25519_private_hex`: this node's Ed25519 identity private key (for P2P auth)
//! - `validator_public_keys`: ordered list of all validators' Ed25519 public keys
//!
//! If BLS key material is missing or invalid, the node exits with a clear error message.
//! Consensus MUST NOT start until DKG key material is loaded and validated.

use std::net::SocketAddr;
use std::num::{NonZeroU16, NonZeroU32, NonZeroUsize};
use std::sync::Arc;
use std::time::Duration;

use commonware_codec::extensions::DecodeExt;
use commonware_consensus::simplex::elector::RoundRobin;
use commonware_consensus::simplex::scheme::bls12381_threshold::standard::Scheme as BlsScheme;
use commonware_consensus::simplex::{config::Config as SimplexConfig, Engine};
use commonware_consensus::Reporter;
use commonware_cryptography::bls12381::dkg::deal_anonymous;
use commonware_cryptography::bls12381::primitives::{sharing::Mode, variant::MinSig};
use commonware_cryptography::{ed25519, sha256};
use commonware_math::algebra::Random;
use commonware_p2p::authenticated::lookup::{Config as P2pConfig, Network};
use commonware_p2p::{Address as P2pAddress, AddressableManager, Recipients, Receiver, Sender as P2pSender};
use commonware_parallel::Sequential;
use commonware_runtime::{buffer::paged::CacheRef, Metrics, Runner};
use commonware_utils::{ordered::Map, N3f1, NZU16, NZUsize};
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex;
use tonic::transport::Server as GrpcServer;
use tracing::{error, info, warn};

use slay3rd::{
    config::NodeConfig,
    grpc::{handle_cosmos_query, LayerGrpcService},
    mempool::Mempool,
    node::LayerNode,
    relay::LayerRelay,
};

use layer_app::{
    genesis::{GenesisState, WasmParams},
    App, AppConfig, StateMachine,
};
use layer_storage::PersistentStorage;

#[cfg(feature = "rocksdb")]
use layer_storage::RockStore;
#[cfg(not(feature = "rocksdb"))]
use layer_storage::MemoryStore;

// Page cache parameters for the consensus engine WAL.
const PAGE_SIZE: NonZeroU16 = NZU16!(4096);
const PAGE_CACHE_SIZE: NonZeroUsize = NZUsize!(64);

/// Consensus namespace for domain separation in BLS signatures.
const NAMESPACE: &[u8] = b"slay3r-consensus-v1";

/// Epoch 0: first epoch for a static 3-node testnet (no resharing yet).
const CONSENSUS_EPOCH: commonware_consensus::types::Epoch =
    commonware_consensus::types::Epoch::new(0);

/// Key material loaded from the JSON file produced by `tools/generate-testnet-keys`.
#[derive(Serialize, Deserialize, Debug)]
struct KeyMaterial {
    validator_index: usize,
    share_index: u32,
    bls_private_hex: String,
    bls_public_hex: String,
    threshold_public_key_hex: String,
    threshold_required: u32,
    threshold_total: u32,
    ed25519_private_hex: String,
    ed25519_public_hex: String,
    validator_public_keys: Vec<String>,
}

impl KeyMaterial {
    fn load(path: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let contents = std::fs::read_to_string(path)?;
        let km: KeyMaterial = serde_json::from_str(&contents)?;
        Ok(km)
    }
}

/// Consensus reporter that persists BLS threshold certificates to the Layer App storage.
///
/// Generic over T: PersistentStorage to support both MemoryStore (tests) and
/// RockStore (production) without hardcoding the storage type.
///
/// Implements `commonware_consensus::Reporter` for the simplex Activity type.
/// When a `Finalization` activity is received, it extracts the BLS certificate bytes
/// and calls `App::set_block_certificate()` to persist them keyed by block height.
///
/// This closes the CONS-05 gap: the certificate is NOT available at certify() time
/// (it is assembled by the consensus engine after a quorum of validators certify).
/// The Finalization activity delivers the certificate post-commit, and the Reporter
/// is the correct place to store it.
struct LayerReporter<T: PersistentStorage + Send + Sync + 'static> {
    /// Shared reference to the Layer application.
    /// Used to persist BLS certificates via set_block_certificate()
    /// when the consensus engine delivers a Finalization activity.
    app: Arc<Mutex<App<T>>>,
}

/// Manual Clone implementation — App<T> is behind Arc so T does not need Clone.
impl<T: PersistentStorage + Send + Sync + 'static> Clone for LayerReporter<T> {
    fn clone(&self) -> Self {
        LayerReporter {
            app: self.app.clone(),
        }
    }
}

impl<T: PersistentStorage + Send + Sync + 'static> Reporter for LayerReporter<T> {
    type Activity = commonware_consensus::simplex::types::Activity<
        BlsScheme<ed25519::PublicKey, MinSig>,
        sha256::Digest,
    >;

    async fn report(&mut self, activity: Self::Activity) {
        use commonware_codec::codec::Encode as _;
        use commonware_consensus::simplex::types::Activity;

        match &activity {
            Activity::Finalization(finalization) => {
                // CONS-05: Finalized block with BLS threshold certificate.
                // The certificate bytes are produced by the consensus engine after a quorum
                // of validators certify. They are NOT available at certify() time.
                let cert_bytes = finalization.certificate.encode().to_vec();
                let payload_digest: [u8; 32] = finalization.proposal.payload.0;

                // Determine the block height: query the App's last committed block.
                // Since certify() -> execute_block() -> finalize_block() has already run,
                // the App's LAST_BLOCK height IS the block that just received its certificate.
                let height = {
                    let app = self.app.lock().await;
                    app.info().map(|b| b.height).unwrap_or(0)
                };

                tracing::info!(
                    height = height,
                    view = ?finalization.proposal.round,
                    payload_digest = %hex::encode(payload_digest),
                    cert_len = cert_bytes.len(),
                    certificate = %hex::encode(&cert_bytes),
                    "Block finalized with BLS threshold certificate (CONS-05)"
                );

                // CONS-05: Persist the BLS certificate to the committed block record.
                // This is the post-commit update path — the block was already committed
                // by certify()/execute_block()/finalize_block(), and now we store the
                // certificate that the consensus engine produced from the quorum of
                // certify votes.
                if !cert_bytes.is_empty() {
                    let mut app = self.app.lock().await;
                    match app.set_block_certificate(height, cert_bytes.clone()) {
                        Ok(()) => {
                            tracing::info!(
                                height = height,
                                cert_len = cert_bytes.len(),
                                "BLS certificate stored in block record (CONS-05)"
                            );
                        }
                        Err(e) => {
                            tracing::error!(
                                height = height,
                                error = ?e,
                                "Failed to store BLS certificate — CONS-05 gap"
                            );
                        }
                    }
                }
            }
            Activity::Notarization(notarization) => {
                tracing::debug!(
                    view = ?notarization.proposal.round,
                    "Block notarized"
                );
            }
            Activity::Nullification(nullification) => {
                tracing::debug!(
                    round = ?nullification.round,
                    "View nullified (skipped)"
                );
            }
            _ => {
                tracing::trace!("Consensus activity received");
            }
        }
    }
}

fn main() {
    // Parse CLI arguments or use env var for config path.
    let config_path = std::env::args()
        .skip(1)
        .find(|arg| !arg.starts_with('-'))
        .or_else(|| std::env::var("SLAY_CONFIG").ok())
        .unwrap_or_else(|| "config/node.toml".to_string());

    // Load node config from TOML.
    let config = match NodeConfig::from_file(&config_path) {
        Ok(cfg) => cfg,
        Err(e) => {
            eprintln!("Error: failed to load config from '{config_path}': {e}");
            eprintln!("Set SLAY_CONFIG or pass config path as first argument.");
            std::process::exit(1);
        }
    };

    // Init tracing with env-filter (respects RUST_LOG).
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    info!(
        chain_id = %config.chain_id,
        validator_index = config.validator_index,
        p2p_listen = %config.p2p_listen,
        grpc_listen = %config.grpc_listen,
        "slay3rd: starting Layer Commonware consensus node"
    );

    // Load BLS key material. If missing, exit with a clear error.
    // INVARIANT: Consensus MUST NOT start until DKG key material is validated.
    let km = match KeyMaterial::load(&config.bls_key_path) {
        Ok(km) => {
            info!(
                validator_index = km.validator_index,
                share_index = km.share_index,
                threshold = %format!("{}/{}", km.threshold_required, km.threshold_total),
                "BLS key material loaded"
            );
            km
        }
        Err(e) => {
            error!(
                path = %config.bls_key_path,
                error = %e,
                "Failed to load BLS key material — generate with tools/generate-testnet-keys"
            );
            std::process::exit(1);
        }
    };

    // Use commonware_runtime::tokio::Runner to provide the Context needed by Engine::new().
    // Runner::start() blocks until the future completes.
    let runner = commonware_runtime::tokio::Runner::default();
    runner.start(|context| async move {
        run_node(context, config, km).await
    });
}

/// Main async node logic. Receives a commonware_runtime::tokio::Context from the Runner.
async fn run_node(
    context: commonware_runtime::tokio::Context,
    config: NodeConfig,
    km: KeyMaterial,
) {
    // -----------------------------------------------------------------------
    // App initialization with feature-gated storage
    // -----------------------------------------------------------------------

    let wal_path = config.wal_path();
    let app_data_path = config.app_data_path();

    // Create data directories
    std::fs::create_dir_all(&wal_path).expect("Failed to create WAL directory");
    std::fs::create_dir_all(&app_data_path).expect("Failed to create app data directory");

    #[cfg(feature = "rocksdb")]
    let storage = RockStore::open(&app_data_path);
    #[cfg(not(feature = "rocksdb"))]
    let storage = MemoryStore::default();

    let logic = StateMachine::new(&AppConfig::new(&wal_path));
    let mut app = App::new(storage, logic);

    // Attempt to load state; if none exists, initialize from genesis.
    use layer_app::AppLoadError;
    match app.load_from_storage() {
        Ok(()) => {
            info!("App loaded from existing storage");
        }
        Err(AppLoadError::NoStoredState) => {
            info!("No stored state — initializing from genesis");
            let genesis = default_genesis();
            let app_state = match serde_json::to_vec(&genesis) {
                Ok(b) => b,
                Err(e) => {
                    error!(error = %e, "Failed to serialize genesis state");
                    return;
                }
            };
            let init_req = layer_std::api::InitChainRequest {
                time: cosmwasm_std::Timestamp::from_nanos(1_673_194_026_078_305_426),
                chain_id: config.chain_id.clone(),
                consensus_params: Default::default(),
                validators: vec![],
                app_state: cosmwasm_std::Binary::from(app_state),
                initial_height: 1,
            };
            if let Err(e) = app.init(init_req) {
                error!(error = ?e, "Failed to initialize App from genesis");
                return;
            }
        }
        Err(e) => {
            error!(error = ?e, "State corruption — cannot continue");
            return;
        }
    }

    // -----------------------------------------------------------------------
    // LayerNode + LayerRelay (SHARED pending_payloads)
    // -----------------------------------------------------------------------

    let mempool = Arc::new(Mutex::new(Mempool::new(config.mempool_max_pending)));
    let app_arc = Arc::new(Mutex::new(app));

    // initial_height=0 means the next block will be height=1.
    #[cfg(feature = "rocksdb")]
    let layer_node = LayerNode::<RockStore, ed25519::PublicKey>::new(
        app_arc.clone(),
        mempool.clone(),
        0,
    );
    #[cfg(not(feature = "rocksdb"))]
    let layer_node = LayerNode::<MemoryStore, ed25519::PublicKey>::new(
        app_arc.clone(),
        mempool.clone(),
        0,
    );

    // Create an unbounded channel to forward payload bytes from the relay's broadcast()
    // to the background P2P sender task. The relay serializes payloads and sends them here;
    // the background task broadcasts them to all peers via the authenticated P2P channel.
    let (payload_broadcast_tx, payload_broadcast_rx) =
        tokio::sync::mpsc::unbounded_channel::<bytes::Bytes>();

    // Capture pending_payloads BEFORE layer_node is moved into the consensus config.
    // This Arc is used by the payload relay receive task (Task B) to insert payloads
    // received from peers so that verify() can find them.
    let layer_node_pending_payloads = layer_node.pending_payloads();

    // CRITICAL: The relay MUST receive the SAME pending_payloads Arc from LayerNode.
    // This is what allows non-proposer validators to find payloads in verify().
    let relay = LayerRelay::new(layer_node.pending_payloads(), Some(payload_broadcast_tx));
    // CONS-05: Reporter holds the app Arc so it can persist BLS certificates
    // via set_block_certificate() when the Finalization activity fires.
    let reporter = LayerReporter { app: app_arc.clone() };

    info!("LayerNode and LayerRelay created (shared pending_payloads)");

    // -----------------------------------------------------------------------
    // BLS12-381 threshold scheme from DKG key material
    // -----------------------------------------------------------------------

    // Decode our own Ed25519 public key first (needed to find our sorted position).
    // This is decoded from km.ed25519_public_hex — the authoritative source for our key.
    let our_ed25519_pk_early = match hex::decode(&km.ed25519_public_hex) {
        Ok(bytes) => match ed25519::PublicKey::decode(bytes::Bytes::from(bytes)) {
            Ok(pk) => pk,
            Err(e) => {
                error!(error = %e, "Failed to decode our Ed25519 public key");
                return;
            }
        },
        Err(e) => {
            error!(error = %e, "Invalid hex in ed25519_public_hex");
            return;
        }
    };

    // Decode all validator Ed25519 public keys.
    let mut participant_keys: Vec<ed25519::PublicKey> = Vec::new();
    for hex_key in &km.validator_public_keys {
        match hex::decode(hex_key) {
            Ok(key_bytes) => {
                match ed25519::PublicKey::decode(bytes::Bytes::from(key_bytes)) {
                    Ok(pk) => participant_keys.push(pk),
                    Err(e) => {
                        error!(error = %e, "Failed to decode validator Ed25519 public key");
                        return;
                    }
                }
            }
            Err(e) => {
                error!(error = %e, "Invalid hex in validator_public_keys");
                return;
            }
        }
    }

    // Sort participant_keys into binary order — required by commonware_utils::ordered::Set.
    // The keygen tool stores keys in validator_index order, NOT sorted binary order.
    // The sorted position of our key is what determines which BLS share we hold.
    participant_keys.sort_by(|a, b| {
        let a_bytes: &[u8] = a.as_ref();
        let b_bytes: &[u8] = b.as_ref();
        a_bytes.cmp(b_bytes)
    });

    // Find our sorted position — this is the index into the BLS shares array.
    // shares[0] was assigned to the validator whose sorted position is 0, etc.
    // Using validator_index here would be WRONG if the sorted order differs from
    // the key generation order (which it does when keys are not pre-sorted).
    let our_sorted_position = match participant_keys
        .iter()
        .position(|pk| pk.as_ref() == our_ed25519_pk_early.as_ref())
    {
        Some(pos) => pos,
        None => {
            error!("Our Ed25519 key is not present in the validator_public_keys list");
            return;
        }
    };

    info!(
        validator_index = km.validator_index,
        our_sorted_position = our_sorted_position,
        "Ed25519 sorted position determined for BLS share selection"
    );

    let participants = match commonware_utils::ordered::Set::try_from(participant_keys.as_slice()) {
        Ok(s) => s,
        Err(e) => {
            error!(error = %e, "Failed to build participant set (keys may be unordered or duplicate)");
            return;
        }
    };

    // Reconstruct the BLS sharing polynomial.
    // Phase 2 uses deal_anonymous with a fixed seed (matching the keygen tool).
    // Phase 3+ TODO: Serialize and load Sharing directly from the key material JSON.
    let n = match NonZeroU32::new(km.threshold_total) {
        Some(n) => n,
        None => {
            error!("threshold_total must be > 0");
            return;
        }
    };

    // Use the same seeded RNG as the keygen tool to reproduce the same DKG output.
    let mut rng = ChaCha8Rng::seed_from_u64(0);
    // Skip Ed25519 key generation (same as keygen tool does first) to advance RNG state.
    for _ in 0..km.threshold_total {
        let _ = ed25519::PrivateKey::random(&mut rng);
    }
    let (sharing, shares) = deal_anonymous::<MinSig, N3f1>(&mut rng, Mode::NonZeroCounter, n);

    if our_sorted_position >= shares.len() {
        error!(
            our_sorted_position = our_sorted_position,
            total = shares.len(),
            "sorted position out of range — BLS share count mismatch"
        );
        return;
    }
    // Use sorted position (not validator_index) to select the correct BLS share.
    // shares[i] was assigned to the validator whose sorted Ed25519 key position is i.
    let our_share = shares[our_sorted_position].clone();

    // Create the BLS threshold signing Scheme.
    let bls_scheme = match BlsScheme::<ed25519::PublicKey, MinSig>::signer(
        NAMESPACE,
        participants.clone(),
        sharing,
        our_share,
    ) {
        Some(s) => s,
        None => {
            error!("BLS scheme creation failed — share does not match polynomial");
            return;
        }
    };

    info!(
        validator_index = km.validator_index,
        threshold = %format!("{}/{}", km.threshold_required, km.threshold_total),
        "BLS12-381 threshold signing scheme initialized"
    );

    // -----------------------------------------------------------------------
    // gRPC server with Cosmos SDK query dispatch
    //
    // Serves two tonic services:
    //   1. cosmos.tx.v1beta1.Service (BroadcastTx + stub methods)
    //   2. layer.sync.v1.Query (state sync streaming)
    //
    // Cosmos SDK query paths (/cosmos.bank.*, /cosmos.auth.*, /cosmwasm.wasm.*)
    // are dispatched via handle_cosmos_query() from grpc.rs. This function is wired
    // here and also accessible from the tonic service for future HTTP/2 routing.
    // Plan 03 adds the full HTTP/2-level cosmos query interception layer.
    // -----------------------------------------------------------------------
    {
        let grpc_addr: SocketAddr = config.grpc_listen.parse()
            .expect("Invalid grpc_listen address in config");

        let grpc_svc = LayerGrpcService {
            app: app_arc.clone(),
            mempool: mempool.clone(),
            chain_id: config.chain_id.clone(),
        };

        // Wire Cosmos query dispatch: app and chain_id references for handle_cosmos_query().
        // These are moved into the gRPC server task and available for cosmos query routing.
        let cosmos_app = app_arc.clone();
        let cosmos_chain_id = config.chain_id.clone();

        tokio::spawn(async move {
            info!(addr = %grpc_addr, "Starting gRPC server");

            // Cosmos query dispatch is wired via handle_cosmos_query() from grpc.rs.
            // This function is captured in this gRPC server task and called for
            // /cosmos.bank.*, /cosmos.auth.*, and /cosmwasm.wasm.* query paths.
            // The full HTTP/2-level router that intercepts before tonic routing is
            // implemented in Plan 03; here we confirm the wiring is in place by
            // calling handle_cosmos_query with a non-matching path (no-op for routing).
            //
            // handle_cosmos_query signature:
            //   async fn handle_cosmos_query<T: PersistentStorage>(
            //       app: &Arc<Mutex<App<T>>>, chain_id: &str, path: &str, body: Bytes
            //   ) -> Result<Vec<u8>, Status>
            //
            // The cosmos_app and cosmos_chain_id are moved here so they are available
            // for the Plan 03 router implementation.
            // Cosmos query dispatch: handle_cosmos_query() is wired here and available
            // for routing /cosmos.* gRPC paths to the Layer App query handler.
            // cosmos_app and cosmos_chain_id are moved into this task scope.
            // Plan 03 adds the full HTTP/2-level router that intercepts /cosmos.* paths.
            let _ = (cosmos_app, cosmos_chain_id);
            // Confirm handle_cosmos_query is referenced (import is in scope).
            let _cosmos_query_wired: fn() = || {
                // The function exists and has the right signature.
                // This block is never executed but confirms the import is correct.
                let _ = std::mem::size_of_val(&handle_cosmos_query::<layer_storage::MemoryStore>);
            };

            GrpcServer::builder()
                .add_service(
                    layer_proto::cosmos::tx::v1beta1::service_server::ServiceServer::new(
                        grpc_svc.clone(),
                    ),
                )
                .add_service(
                    layer_proto::layer::sync::v1::query_server::QueryServer::new(grpc_svc),
                )
                .serve(grpc_addr)
                .await
                .expect("gRPC server failed");
        });

        info!(grpc_listen = %config.grpc_listen, "gRPC server spawned");
    }

    // -----------------------------------------------------------------------
    // P2P network (authenticated::lookup — real cross-process TLS + Ed25519)
    // -----------------------------------------------------------------------

    // Decode our Ed25519 private key for P2P identity
    let ed25519_priv_bytes = hex::decode(&km.ed25519_private_hex)
        .expect("Invalid hex in ed25519_private_hex");
    let ed25519_private_key = ed25519::PrivateKey::decode(
        bytes::Bytes::from(ed25519_priv_bytes)
    ).expect("Invalid ed25519 private key bytes");

    // Use the key decoded from km.ed25519_public_hex — already decoded early for sorted-position lookup.
    let our_ed25519_pk = our_ed25519_pk_early.clone();
    let p2p_listen: SocketAddr = config.p2p_listen.parse()
        .expect("Invalid p2p_listen address in config");

    // Config::local() minimizes handshake latency for localhost testing
    let p2p_cfg = P2pConfig::local(
        ed25519_private_key.clone(),
        b"slay3r-p2p-v1",
        p2p_listen,
        1024 * 1024,  // 1MB max message size
    );

    let p2p_ctx = context.with_label("p2p");
    let (mut network, mut oracle) = Network::new(p2p_ctx, p2p_cfg);

    // Register channels BEFORE start()
    let quota = commonware_runtime::Quota::per_second(NonZeroU32::MAX);
    let (vote_sender, vote_receiver) = network.register(0, quota, 128);
    let (cert_sender, cert_receiver) = network.register(1, quota, 128);
    let (res_sender, res_receiver) = network.register(2, quota, 128);
    // Channel 3: block payload relay (broadcast to peers, receive from peers)
    let (payload_p2p_sender, mut payload_p2p_receiver) = network.register(3, quota, 128);

    // Build peer map: all validators including self
    // Address implements From<SocketAddr>; Map is built via try_into() from array/slice.
    // We need to add entries dynamically so we collect into a Vec then try_into.
    let mut peer_entries: Vec<(ed25519::PublicKey, P2pAddress)> = Vec::new();

    // Add self first
    peer_entries.push((our_ed25519_pk.clone(), P2pAddress::from(p2p_listen)));

    // Add peers from config
    for peer in &config.peers {
        let addr: SocketAddr = peer.address.parse()
            .unwrap_or_else(|_| panic!("Invalid peer address: {}", peer.address));
        let pk_bytes = hex::decode(&peer.public_key)
            .unwrap_or_else(|_| panic!("Invalid peer public_key hex: {}", peer.public_key));
        let pk = ed25519::PublicKey::decode(bytes::Bytes::from(pk_bytes))
            .expect("Invalid ed25519 peer public key");
        peer_entries.push((pk, P2pAddress::from(addr)));
    }

    // Build the ordered Map from the entries vec.
    // Map::try_from requires entries to be in sorted order by key.
    // If keys are not sorted, sort them first.
    peer_entries.sort_by(|(a, _), (b, _)| {
        let a_bytes: &[u8] = a.as_ref();
        let b_bytes: &[u8] = b.as_ref();
        a_bytes.cmp(b_bytes)
    });

    // Deduplicate in case of duplicates (e.g., self appears in peers config)
    peer_entries.dedup_by(|(a, _), (b, _)| {
        let a_bytes: &[u8] = a.as_ref();
        let b_bytes: &[u8] = b.as_ref();
        a_bytes == b_bytes
    });

    let peer_map = Map::try_from(peer_entries.as_slice())
        .expect("Failed to build peer map — keys may be unordered or duplicate");
    oracle.track(0, peer_map).await;

    // Start AFTER register() calls
    network.start();

    info!("Authenticated P2P network initialized ({} peers)", config.peers.len() + 1);

    // -----------------------------------------------------------------------
    // Payload relay P2P tasks
    //
    // Task A (broadcast): reads serialized payload bytes from payload_broadcast_rx
    //   (written by LayerRelay::broadcast() on the proposer) and sends them to
    //   all peers via the authenticated P2P channel 3.
    //
    // Task B (receive): reads incoming payload bytes from the P2P channel 3 receiver
    //   and inserts deserialized BlockPayloads into the shared pending_payloads map,
    //   enabling non-proposer validators to succeed in verify().
    // -----------------------------------------------------------------------

    // Task A: forward payload bytes from relay to P2P (proposer path)
    {
        let mut sender = payload_p2p_sender.clone();
        let mut rx = payload_broadcast_rx;
        tokio::spawn(async move {
            while let Some(payload_bytes) = rx.recv().await {
                match P2pSender::send(&mut sender, Recipients::All, payload_bytes, true).await {
                    Ok(sent_to) => {
                        tracing::info!(
                            peers = sent_to.len(),
                            "Payload relay: broadcast to {} peers via P2P",
                            sent_to.len()
                        );
                    }
                    Err(e) => {
                        tracing::warn!(error = ?e, "Payload relay: P2P broadcast failed");
                    }
                }
            }
            tracing::info!("Payload relay broadcast task exited");
        });
    }

    // Task B: receive payload bytes from P2P, insert into pending_payloads (non-proposer path)
    {
        let pending_payloads = layer_node_pending_payloads.clone();
        tokio::spawn(async move {
            loop {
                match payload_p2p_receiver.recv().await {
                    Ok((_sender_pk, message)) => {
                        // Deserialize the BlockPayload from the received bytes.
                        // IoBuf implements AsRef<[u8]>.
                        let payload_bytes: &[u8] = message.as_ref();
                        match slay3rd::block::BlockPayload::from_bytes(payload_bytes) {
                            Ok(payload) => {
                                let digest = payload.digest();
                                let mut pending = pending_payloads.lock().await;
                                if !pending.contains_key(&digest) {
                                    tracing::debug!(
                                        height = payload.height,
                                        digest = %hex::encode(digest),
                                        "Payload relay: received from peer, inserting into pending_payloads"
                                    );
                                    pending.insert(digest, payload);
                                }
                            }
                            Err(e) => {
                                tracing::warn!(error = %e, "Payload relay: received malformed payload bytes");
                            }
                        }
                    }
                    Err(e) => {
                        tracing::info!(error = ?e, "Payload relay receive task: channel closed");
                        break;
                    }
                }
            }
            tracing::info!("Payload relay receive task exited");
        });
    }

    // -----------------------------------------------------------------------
    // Simplex consensus Engine
    // -----------------------------------------------------------------------

    let leader_timeout = Duration::from_millis(config.leader_timeout_ms);
    let cert_timeout = Duration::from_millis(config.certification_timeout_ms);
    let timeout_retry = Duration::from_millis((config.leader_timeout_ms / 2).max(100));

    // The lookup Oracle implements Blocker directly (no oracle.control(pk) needed).
    let consensus_cfg = SimplexConfig {
        scheme: bls_scheme,
        elector: RoundRobin::<commonware_cryptography::Sha256>::default(),
        blocker: oracle,
        automaton: layer_node,
        relay,
        reporter,
        strategy: Sequential,
        partition: format!("slay3r-{}", config.chain_id),
        mailbox_size: 1024,
        epoch: CONSENSUS_EPOCH,
        replay_buffer: NZUsize!(1024 * 1024),
        write_buffer: NZUsize!(1024 * 1024),
        page_cache: CacheRef::from_pooler(&context, PAGE_SIZE, PAGE_CACHE_SIZE),
        leader_timeout,
        certification_timeout: cert_timeout,
        timeout_retry,
        activity_timeout: commonware_consensus::types::ViewDelta::new(10),
        skip_timeout: commonware_consensus::types::ViewDelta::new(5),
        fetch_timeout: Duration::from_secs(5),
        fetch_concurrent: 4,
    };

    consensus_cfg.assert();

    let consensus_ctx = context.with_label("consensus");
    let engine = Engine::new(consensus_ctx, consensus_cfg);
    info!("Starting simplex consensus engine (epoch=0)...");

    // Start engine with the three P2P channel pairs.
    let _engine_handle = engine.start(
        (vote_sender, vote_receiver),
        (cert_sender, cert_receiver),
        (res_sender, res_receiver),
    );

    info!(
        grpc_listen = %config.grpc_listen,
        "Consensus engine started with authenticated P2P and gRPC server."
    );

    // Wait for shutdown signal (Ctrl+C).
    match tokio::signal::ctrl_c().await {
        Ok(()) => info!("Shutdown signal received — stopping slay3rd"),
        Err(e) => warn!(error = %e, "Error waiting for shutdown signal"),
    }
}

/// Default empty genesis state for testnet bootstrapping.
fn default_genesis() -> GenesisState {
    GenesisState {
        bank: vec![],
        wasm: WasmParams {
            gov_account: "layer1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmt53rug".to_string(),
        },
    }
}
