[workspace]
members = ["app/*", "packages/*"]
# remove this temporarily as it has huge build dependencies (around 330 for lcd, 230 for cosmos, 110 for others)
exclude = ["app/lcd"]

[workspace.package]
edition       = "2021"
version       = "0.1.0"
license       = "CC-BY-NC-ND-4.0"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[workspace.dependencies]
thiserror    = "1.0.38"
cosmwasm-std = "1.2.4"
cosmwasm-schema = "1.2.4"
cosmwasm-crypto = "1.2.4"
cw-storage-plus = "1.0.1"
cw-utils = "1.0.1"
serde = { version = "1.0.160", features = ["derive"]}
itertools = "0.10.5"
sha2 = "0.10.6"
ripemd = "0.1.3"
parking_lot = "0.12.1"

pulsar-app = { path = "./packages/app" }
pulsar-cosmos = { path = "./packages/cosmos" }
pulsar-std = { path = "./packages/std" }
pulsar-storage = { path = "./packages/storage" }

tendermint-abci = { git = "https://github.com/informalsystems/tendermint-rs.git", rev = "bdef9884221a850323f98b3fa2b9b7471f5e8437"}
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs.git", rev = "bdef9884221a850323f98b3fa2b9b7471f5e8437"}

tracing = "0.1.37"
opentelemetry = "0.19.0"
opentelemetry-jaeger = "0.18.0"
tracing-opentelemetry = "0.19.0"

[profile.release]
# temporary to speed up testing
# lto              = true
lto              = false
opt-level        = 3
overflow-checks  = true
