[workspace]
members = ["app/*", "contracts/*", "packages/*"]
exclude = ["tools/proto-compiler"]

[workspace.package]
edition       = "2021"
version       = "0.2.0"
license       = "CC-BY-NC-ND-4.0"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[workspace.dependencies]
thiserror    = "1.0.38"

cosmwasm-std = "1.5.0"
cosmwasm-schema = "1.5.0"
cosmwasm-crypto = "1.5.0"
cosmwasm-vm = { version = "1.5.0", default-features = false, features = ["iterator"] }

cw-storage-plus = "1.2.0"
cw-utils = "1.0.1"

serde = { version = "1.0.160", features = ["derive"]}
itertools = "0.11.0"
sha2 = "0.10.6"
ripemd = "0.1.3"
parking_lot = "0.12.1"
hex-literal = "0.4.1"
bytes = { version = "1.4.0", default_features = false, features = ["serde"] }
prost = { version = "0.12.1" }
prost-types = { version = "0.12.1" }
tonic = { version = "0.10.2", default_features = false, features = ["codegen", "transport", "prost"] }

pulsar-abci = { path = "./packages/abci" }
pulsar-app = { path = "./packages/app" }
pulsar-cosmos = { path = "./packages/cosmos" }
pulsar-proto = { path = "./packages/proto" }
pulsar-std = { path = "./packages/std" }
pulsar-storage = { path = "./packages/storage" }

tc-echo = { path = "./contracts/echo" }
tc-caller = { path = "./contracts/caller" }

tendermint = "0.34.0"
tendermint-abci = "0.34.0"
tendermint-proto = "0.34.0"
tendermint-rpc = "0.34.0"

tracing = "0.1.37"
opentelemetry = "0.19.0"
opentelemetry-jaeger = "0.18.0"
tracing-opentelemetry = "0.19.0"

cosmrs = {version = "0.13.0", default_features = false, features = ["cosmwasm"] }
cosmos-sdk-proto = { version = "0.18.0",  features = ["cosmwasm"] }


[profile.release]
# temporary to speed up testing
# lto              = true
lto              = false
opt-level        = 3
overflow-checks  = true

# We have a lot of heavy dependencies like wasmer / cosmwasm-vm and tests lag if they
# are not optimized. They should be cached the first time and not need expensive re-compiles,
# so this shouldn't slow down dev loop much
# (Note this doesn't apply to workspace, just dependencies)

# DEV: you can uncomment locally
# [profile.test.package."*"]
# opt-level        = 3

[profile.release.package.tc-echo]
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
# TODO: enabling these seems to break cargo...
# rpath = false
# lto = true
# panic = 'abort'
