version: '3'

volumes:
  pulsar_data:
    external: true
  comet_data:
    external: true

services:
  pulsariumd:
    image: "pulsar/pulsariumd:latest"
    expose:
      - "26658"
    volumes:
      - pulsar_data:/root/.pulsar
  cometbft:
    image: "cometbft/cometbft:v0.38.0-rc2"
    ports:
      - "26656:26656"
      - "26657:26657"
    command: ["start", "--proxy_app", "tcp://pulsariumd:26658"]
    volumes:
      - comet_data:/cometbft
  jaeger:
    image: jaegertracing/all-in-one:1.46
    expose:
      - "6831/udp" 
      - "6832/udp" 
      - "14268"
    ports: 
      - "8080:16686"
