# Usage:
# ./scripts/build_docker.sh
# ./scripts/reset_volumes.sh
# docker compose up
# cd integration && npm ci &&  npm run test
# open http://localhost:8000

# version: '3.8'

volumes:
  lay3r_data:
    external: true
  comet_data:
    external: true

services:
  lay3r:
    image: "ghcr.io/lay3rlabs/lay3rd:latest"
    expose:
      # abci server only for cometbft
      - "26658"
    ports:
      # open grpc server
      - "9090:9090"
    volumes:
      - lay3r_data:/root/.pulsar
    command: ["pulsariumd"]
    depends_on:
      - jaeger
  cometbft:
    image: "cometbft/cometbft:v0.38.0"
    expose:
      # for pulsariumd grpc callbacks
      - "26657"
    ports:
      - "26656:26656"
      - "26657:26657"
    command: ["start", "--proxy_app", "tcp://lay3r:26658"]
    volumes:
      - comet_data:/cometbft
    depends_on:
      - lay3r
  jaeger:
    image: jaegertracing/all-in-one:1.46
    expose:
      - "6831/udp"
      - "6832/udp"
      - "14268"
    ports:
      - "8080:16686"
  gateway:
    image: "ghcr.io/lay3rlabs/gateway:latest"
    ports:
      # rest port
      - "1317:1317"
    # connect to the grpc endpoint on lay3r
    command: ["/app", "-grpc-server-endpoint", "lay3r:9090"]
    depends_on:
      - lay3r
  # vectis:
  #   image: "pulsar/vectis-todo:latest"
  #   ports:
  #     # expose web app
  #     - "8000:80"
