# docker compose -f docker-compose.yml -f jaeger-compose.yml up
# docker compose -f docker-compose.yml -f jaeger-compose.yml down

# http://localhost:8080  - Jaeger UI
# http://localhost:9200  - Elastic Search API
# http://localhost:9200/_search  - Check for data

volumes:
  esdata:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    ports:
      - "127.0.0.1:9200:9200"
      # - "127.0.0.1:9300:9300"
    restart: on-failure
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  # Optional ElasticSearch UI (on Port 5601 - click Discovery and create a view)
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.15.1
  #   ports:
  #     - "127.0.0.1:5601:5601"
  #   restart: on-failure

  # Important to name this jaeger (not jaeger-collector) as this is the host slayerd is sending traces to
  # Overrides the default all-in-one memory DB in the main docker-compose.yml
  jaeger:
    image: jaegertracing/jaeger-collector:1.59
    expose: !override
      - "14269"
      - "14268"
      - "14267"
      - "14250"
      - "9411"
    ports: !reset
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--log-level=error"
    ]
    depends_on:
      - elasticsearch

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.59
    hostname: jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    expose:
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
      - "5778"
    # ports:
    #   - "5775:5775/udp"
    #   - "6831:6831/udp"
    #   - "6832:6832/udp"
    #   - "5778:5778"
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    depends_on:
      - jaeger

  jaeger-query:
    image: jaegertracing/jaeger-query:1.59
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    ports:
      - "8080:16686"
      # - "16687:16687"
    restart: on-failure
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug"
    ]
    depends_on:
      - jaeger-agent
