syntax = "proto3";
package layer.sync.v1;

import "google/api/annotations.proto";

// Query defines the gRPC querier service.
service Query {
  rpc Latestheight(QueryLatestHeightRequest) returns (QueryLatestHeightResponse) {
    option (google.api.http).get = "/layer/sync/v1/latest_height";
  }

  rpc CurrentState(StreamCurrentStateRequest) returns (stream WriteData) {
  }

  // TODO: return block by block?
  // Then it is one sequence number with a block of write/read requests
  // Which will map much nicer to the rocksdb implementation
  rpc ChangesSince(StreamChangesSinceRequest) returns (stream BlockWrites) {
  }
}

message QueryLatestHeightRequest {
}

message QueryLatestHeightResponse {
    uint64 height = 1;
}


message StreamCurrentStateRequest {
}

message StreamChangesSinceRequest {
    uint64 height = 1;
}

message BlockWrites {
    uint64 height = 1;
    // TODO: timestamp? app hash?
    repeated StateChange events = 3;
}

message StateChange {
    oneof event {
        WriteData write_state = 1; 
        DeleteData delete_state = 2; 
    }
}

message WriteData {
    string module = 1;
    string bucket = 2;
    // this is split from whatever we use internally - [] for item
    // numbers are stringified. bytes are base64 encoded
    repeated string keys = 3;
    // TODO define this type: just JSON? use protobuf for internal types?
    bytes value = 4;
}

message DeleteData {
    string module = 1;
    string bucket = 2;
    // this is split from whatever we use internally - [] for 
    // numbers are stringified. bytes are base64 encoded
    repeated string keys = 3;
}