// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: layer/sync/v1/query.proto

package syncv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_LatestSequence_FullMethodName = "/layer.sync.v1.Query/LatestSequence"
	Query_CurrentState_FullMethodName   = "/layer.sync.v1.Query/CurrentState"
	Query_ChangesSince_FullMethodName   = "/layer.sync.v1.Query/ChangesSince"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	LatestSequence(ctx context.Context, in *QueryLatestSequenceRequest, opts ...grpc.CallOption) (*QueryLatestSequenceResponse, error)
	CurrentState(ctx context.Context, in *StreamCurrentStateRequest, opts ...grpc.CallOption) (Query_CurrentStateClient, error)
	ChangesSince(ctx context.Context, in *StreamChangesSinceRequest, opts ...grpc.CallOption) (Query_ChangesSinceClient, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) LatestSequence(ctx context.Context, in *QueryLatestSequenceRequest, opts ...grpc.CallOption) (*QueryLatestSequenceResponse, error) {
	out := new(QueryLatestSequenceResponse)
	err := c.cc.Invoke(ctx, Query_LatestSequence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CurrentState(ctx context.Context, in *StreamCurrentStateRequest, opts ...grpc.CallOption) (Query_CurrentStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &Query_ServiceDesc.Streams[0], Query_CurrentState_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &queryCurrentStateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_CurrentStateClient interface {
	Recv() (*WriteData, error)
	grpc.ClientStream
}

type queryCurrentStateClient struct {
	grpc.ClientStream
}

func (x *queryCurrentStateClient) Recv() (*WriteData, error) {
	m := new(WriteData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) ChangesSince(ctx context.Context, in *StreamChangesSinceRequest, opts ...grpc.CallOption) (Query_ChangesSinceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Query_ServiceDesc.Streams[1], Query_ChangesSince_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &queryChangesSinceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_ChangesSinceClient interface {
	Recv() (*BlockWrites, error)
	grpc.ClientStream
}

type queryChangesSinceClient struct {
	grpc.ClientStream
}

func (x *queryChangesSinceClient) Recv() (*BlockWrites, error) {
	m := new(BlockWrites)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	LatestSequence(context.Context, *QueryLatestSequenceRequest) (*QueryLatestSequenceResponse, error)
	CurrentState(*StreamCurrentStateRequest, Query_CurrentStateServer) error
	ChangesSince(*StreamChangesSinceRequest, Query_ChangesSinceServer) error
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) LatestSequence(context.Context, *QueryLatestSequenceRequest) (*QueryLatestSequenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestSequence not implemented")
}
func (UnimplementedQueryServer) CurrentState(*StreamCurrentStateRequest, Query_CurrentStateServer) error {
	return status.Errorf(codes.Unimplemented, "method CurrentState not implemented")
}
func (UnimplementedQueryServer) ChangesSince(*StreamChangesSinceRequest, Query_ChangesSinceServer) error {
	return status.Errorf(codes.Unimplemented, "method ChangesSince not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_LatestSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LatestSequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestSequence(ctx, req.(*QueryLatestSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CurrentState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCurrentStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).CurrentState(m, &queryCurrentStateServer{stream})
}

type Query_CurrentStateServer interface {
	Send(*WriteData) error
	grpc.ServerStream
}

type queryCurrentStateServer struct {
	grpc.ServerStream
}

func (x *queryCurrentStateServer) Send(m *WriteData) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_ChangesSince_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChangesSinceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).ChangesSince(m, &queryChangesSinceServer{stream})
}

type Query_ChangesSinceServer interface {
	Send(*BlockWrites) error
	grpc.ServerStream
}

type queryChangesSinceServer struct {
	grpc.ServerStream
}

func (x *queryChangesSinceServer) Send(m *BlockWrites) error {
	return x.ServerStream.SendMsg(m)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "layer.sync.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LatestSequence",
			Handler:    _Query_LatestSequence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CurrentState",
			Handler:       _Query_CurrentState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ChangesSince",
			Handler:       _Query_ChangesSince_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "layer/sync/v1/query.proto",
}
