[package]
name = "slay3rd"
description = "Rust ABCI app to run slay3r with CometBFT 0.38"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# default = ["no-trace"]
# remove any unneeded baggage
optimize = ["tracing/release_max_level_info"]
# remove exceessive tracing, we often don't want
no-trace = ["tracing/release_max_level_debug"]

[dependencies]
slay3r-abci = { workspace = true }
slay3r-app = { workspace = true, features = ["rocksdb"] }
slay3r-std = { workspace = true }
slay3r-cosmos = { workspace = true }
slay3r-proto = { workspace = true, features = ["server"] }
slay3r-storage = { workspace = true, features = ["rocksdb"] }
cosmwasm-std = { workspace = true }

clap = { version = "4.2.4", features = ["derive"]}
figment = { version = "0.10.8", features = ["env", "toml"]}
serde = { workspace = true }
pico-args = { version = "0.5.0", default-features = false }

tendermint = { workspace = true }
tendermint-proto = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"]}
cosmrs = { workspace = true}

tracing = { workspace = true }
tracing-subscriber = { version="0.3.17", features = ["time", "local-time", "ansi", "parking_lot", "env-filter"]}
thiserror = { workspace = true }
parking_lot = { workspace = true }
sha2 = { workspace = true }

opentelemetry = { workspace = true, features = ["rt-tokio"] }
opentelemetry-jaeger = { workspace = true, features = ["collector_client", "isahc_collector_client", "rt-tokio"] }
tracing-opentelemetry = {workspace = true}

tokio = { version = "1.28.0", features = ["full"] }
bytes = {workspace = true}
prost = { workspace = true }
tonic = { workspace = true }
serde_json = { workspace = true }
tower = "0.4.13"
hex = "0.4.3"
futures = "0.3.30"

[dev-dependencies]
hex-literal = {workspace = true }
