# Build:
#   docker build -t ghcr.io/lay3rlabs/faucet:latest -f Dockerfile.faucet .
# Run:
#   docker run --rm confio/faucet:manual version
#
# During the build step the working directory must be the repo root such that the
# app has access to all installed dependencies.

# update to node 20?
FROM node:20-alpine as build-env
# FROM node:20-slim as build-env

ADD . /app
WORKDIR /app

RUN apk add --update --no-cache alpine-sdk linux-headers build-base gcc libusb-dev python3 py3-pip eudev-dev shadow libusb
RUN ln -sf python3 /usr/bin/python

RUN git clone -b v0.32.3 --depth 1 https://github.com/cosmos/cosmjs.git
WORKDIR /app/cosmjs
RUN rm yarn.lock && yarn install && yarn run build
RUN (cd packages/faucet && SKIP_BUILD=1 yarn pack-node)

# Use Alpine and install Node.js which is 50% smaller than the -alpine version of the node
# image (53 MB including the faucet app).
# FROM debian:12-slim
FROM alpine:3.19
# 3.19 has node 20
# Installs Node.js 16 (https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.19)
RUN apk add --update nodejs

COPY --from=build-env /app/packages/faucet /app/packages/faucet
WORKDIR /app

EXPOSE 8000
ENTRYPOINT ["/app/packages/faucet/bin/cosmos-faucet-dist"]