# docker build . -f docker/Dockerfile.gateway -t ghcr.io/lay3rlabs/gateway:latest
# docker run --rm -it ghcr.io/lay3rlabs/gateway:latest /bin/bash

FROM golang:1.22-bookworm AS build-env

COPY ./packages/cosmossdk/tools/gateway /src/gateway
ENV CGO_ENABLED=0
RUN cd /src/gateway && go build -o /app

# Production stage
# FROM scratch
FROM debian:bookworm-slim
COPY --from=build-env /app /

# ENTRYPOINT ["/app"]
CMD ["/app"]