# docker build . -f docker/Dockerfile.slay3rd -t ghcr.io/lay3rlabs/slay3rd:latest
# docker run --rm -it ghcr.io/lay3rlabs//slay3rd:latest /bin/bash

### BUILDING

FROM rust:1.77-bookworm as builder
WORKDIR /myapp

# This whole pile will pre-build and cache the dependencies, so we just recompile local code below
COPY Cargo.lock Cargo.toml /myapp/
COPY app/slay3rd/Cargo.toml /myapp/app/slay3rd/Cargo.toml
COPY dummy.rs /myapp/app/slay3rd/src/main.rs
COPY contracts/caller/Cargo.toml /myapp/contracts/caller/Cargo.toml
COPY dummy.rs /myapp/contracts/caller/src/lib.rs
COPY contracts/echo/Cargo.toml /myapp/contracts/echo/Cargo.toml
COPY dummy.rs /myapp/contracts/echo/src/lib.rs
COPY packages/abci/Cargo.toml /myapp/packages/abci/Cargo.toml
COPY dummy.rs /myapp/packages/abci/src/lib.rs
COPY packages/app/Cargo.toml /myapp/packages/app/Cargo.toml
COPY dummy.rs /myapp/packages/app/src/lib.rs
COPY packages/cosmos/Cargo.toml /myapp/packages/cosmos/Cargo.toml
COPY dummy.rs /myapp/packages/cosmos/src/lib.rs
COPY packages/proto/Cargo.toml /myapp/packages/proto/Cargo.toml
COPY dummy.rs /myapp/packages/proto/src/lib.rs
COPY packages/std/Cargo.toml /myapp/packages/std/Cargo.toml
COPY dummy.rs /myapp/packages/std/src/lib.rs
COPY packages/storage/Cargo.toml /myapp/packages/storage/Cargo.toml
COPY dummy.rs /myapp/packages/storage/src/lib.rs
RUN cargo build --release --bin slay3rd

# clean up these fake local deps so we compile for real later
RUN rm /myapp/*/*/src/*.rs
RUN rm -rf target/release/.fingerprint/slay3r*

# This build step should just compile the local code and be faster
COPY . .
RUN cargo build --release --bin slay3rd

### PRODUCTION

# Now, pack up that binary in a nice small image
FROM debian:bookworm-slim
RUN apt-get update && apt-get upgrade
RUN apt install -y libcurl4
COPY --from=builder /myapp/target/release/slay3rd /usr/local/bin/slay3rd
EXPOSE 26658
CMD ["slay3rd"]

