# Usage:
# sudo ./scripts/build_docker.sh
# sudo ./scripts/reset_volumes.sh
# sudo docker compose up
# cd integration && npm ci &&  npm run test
# open http://localhost:18080

# http://localhost:36657  - Tendermint RPC
# http://localhost:19090   - gRPC
# http://localhost:11317   - "LCD" / "REST"

volumes:
  peer_lay3r_data:
    external: true
  peer_comet_data:
    external: true

services:
  slay3r:
    image: "ghcr.io/lay3rlabs/slay3rd:latest"
    expose:
      # abci server only for cometbft
      - "36658"
    ports:
      # open grpc server
      - "19090:9090"
    volumes:
      - peer_lay3r_data:/root/.slay3r
    command: ["slay3rd"]
    depends_on:
      - jaeger
    environment:
      - RUST_BACKTRACE=1

  cometbft:
    image: "cometbft/cometbft:v0.38.12"
    ports:
      - "36656:36656"
      - "36657:36657"
    command: ["start", "--proxy_app", "tcp://slay3r:36658"]
    volumes:
      - peer_comet_data:/cometbft
    depends_on:
      - slay3r

  # Default all-memory Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.59
    expose:
      - "6831/udp"
      - "6832/udp"
      - "24268:14268"
    ports:
      - "18080:16686"

  gateway:
    image: "ghcr.io/lay3rlabs/gateway:latest"
    ports:
      # rest port
      - "11317:1317"
    # connect to the grpc endpoint on lay3r
    command: ["/app", "-grpc-server-endpoint", "slay3r:19090"]
    depends_on:
      - slay3r
