// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: cosmwasm/wasm/v1/tx.proto

package wasmv1

import (
	v1beta1 "github.com/lay3rlabs/layer-sdk/gateway/cosmos/base/v1beta1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgStoreCode submit Wasm code to the system
type MsgStoreCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender is the that actor that signed the messages
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// WASMByteCode can be raw or gzip compressed
	WasmByteCode []byte `protobuf:"bytes,2,opt,name=wasm_byte_code,json=wasmByteCode,proto3" json:"wasm_byte_code,omitempty"`
}

func (x *MsgStoreCode) Reset() {
	*x = MsgStoreCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStoreCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStoreCode) ProtoMessage() {}

func (x *MsgStoreCode) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStoreCode.ProtoReflect.Descriptor instead.
func (*MsgStoreCode) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgStoreCode) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgStoreCode) GetWasmByteCode() []byte {
	if x != nil {
		return x.WasmByteCode
	}
	return nil
}

// MsgStoreCodeResponse returns store result data.
type MsgStoreCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// CodeID is the reference to the stored WASM code
	CodeId uint64 `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// Checksum is the sha256 hash of the stored code
	Checksum []byte `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *MsgStoreCodeResponse) Reset() {
	*x = MsgStoreCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgStoreCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStoreCodeResponse) ProtoMessage() {}

func (x *MsgStoreCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStoreCodeResponse.ProtoReflect.Descriptor instead.
func (*MsgStoreCodeResponse) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgStoreCodeResponse) GetCodeId() uint64 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *MsgStoreCodeResponse) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// MsgInstantiateContract create a new smart contract instance for the given
// code id.
type MsgInstantiateContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender is the that actor that signed the messages
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Admin is an optional address that can execute migrations
	Admin string `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	// CodeID is the reference to the stored WASM code
	CodeId uint64 `protobuf:"varint,3,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// Label is optional metadata to be stored with a contract instance.
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// Msg json encoded message to be passed to the contract on instantiation
	Msg []byte `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	// Funds coins that are transferred to the contract on instantiation
	Funds []*v1beta1.Coin `protobuf:"bytes,6,rep,name=funds,proto3" json:"funds,omitempty"`
}

func (x *MsgInstantiateContract) Reset() {
	*x = MsgInstantiateContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInstantiateContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInstantiateContract) ProtoMessage() {}

func (x *MsgInstantiateContract) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInstantiateContract.ProtoReflect.Descriptor instead.
func (*MsgInstantiateContract) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgInstantiateContract) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgInstantiateContract) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

func (x *MsgInstantiateContract) GetCodeId() uint64 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *MsgInstantiateContract) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MsgInstantiateContract) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgInstantiateContract) GetFunds() []*v1beta1.Coin {
	if x != nil {
		return x.Funds
	}
	return nil
}

// MsgInstantiateContract2 create a new smart contract instance for the given
// code id with a predicable address.
type MsgInstantiateContract2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender is the that actor that signed the messages
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Admin is an optional address that can execute migrations
	Admin string `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	// CodeID is the reference to the stored WASM code
	CodeId uint64 `protobuf:"varint,3,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// Label is optional metadata to be stored with a contract instance.
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// Msg json encoded message to be passed to the contract on instantiation
	Msg []byte `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	// Funds coins that are transferred to the contract on instantiation
	Funds []*v1beta1.Coin `protobuf:"bytes,6,rep,name=funds,proto3" json:"funds,omitempty"`
	// Salt is an arbitrary value provided by the sender. Size can be 1 to 64.
	Salt []byte `protobuf:"bytes,7,opt,name=salt,proto3" json:"salt,omitempty"`
	// FixMsg include the msg value into the hash for the predictable address.
	// Default is false
	FixMsg bool `protobuf:"varint,8,opt,name=fix_msg,json=fixMsg,proto3" json:"fix_msg,omitempty"`
}

func (x *MsgInstantiateContract2) Reset() {
	*x = MsgInstantiateContract2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInstantiateContract2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInstantiateContract2) ProtoMessage() {}

func (x *MsgInstantiateContract2) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInstantiateContract2.ProtoReflect.Descriptor instead.
func (*MsgInstantiateContract2) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgInstantiateContract2) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgInstantiateContract2) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

func (x *MsgInstantiateContract2) GetCodeId() uint64 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *MsgInstantiateContract2) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MsgInstantiateContract2) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgInstantiateContract2) GetFunds() []*v1beta1.Coin {
	if x != nil {
		return x.Funds
	}
	return nil
}

func (x *MsgInstantiateContract2) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *MsgInstantiateContract2) GetFixMsg() bool {
	if x != nil {
		return x.FixMsg
	}
	return false
}

// MsgInstantiateContractResponse return instantiation result data
type MsgInstantiateContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address is the bech32 address of the new contract instance.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Data contains bytes to returned from the contract
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgInstantiateContractResponse) Reset() {
	*x = MsgInstantiateContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInstantiateContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInstantiateContractResponse) ProtoMessage() {}

func (x *MsgInstantiateContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInstantiateContractResponse.ProtoReflect.Descriptor instead.
func (*MsgInstantiateContractResponse) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgInstantiateContractResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MsgInstantiateContractResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// MsgInstantiateContract2Response return instantiation result data
type MsgInstantiateContract2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address is the bech32 address of the new contract instance.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Data contains bytes to returned from the contract
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgInstantiateContract2Response) Reset() {
	*x = MsgInstantiateContract2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInstantiateContract2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInstantiateContract2Response) ProtoMessage() {}

func (x *MsgInstantiateContract2Response) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInstantiateContract2Response.ProtoReflect.Descriptor instead.
func (*MsgInstantiateContract2Response) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgInstantiateContract2Response) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MsgInstantiateContract2Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// MsgExecuteContract submits the given message data to a smart contract
type MsgExecuteContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender is the that actor that signed the messages
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Contract is the address of the smart contract
	Contract string `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	// Msg json encoded message to be passed to the contract
	Msg []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	// Funds coins that are transferred to the contract on execution
	Funds []*v1beta1.Coin `protobuf:"bytes,5,rep,name=funds,proto3" json:"funds,omitempty"`
}

func (x *MsgExecuteContract) Reset() {
	*x = MsgExecuteContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgExecuteContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgExecuteContract) ProtoMessage() {}

func (x *MsgExecuteContract) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgExecuteContract.ProtoReflect.Descriptor instead.
func (*MsgExecuteContract) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgExecuteContract) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgExecuteContract) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *MsgExecuteContract) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgExecuteContract) GetFunds() []*v1beta1.Coin {
	if x != nil {
		return x.Funds
	}
	return nil
}

// MsgExecuteContractResponse returns execution result data.
type MsgExecuteContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data contains bytes to returned from the contract
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgExecuteContractResponse) Reset() {
	*x = MsgExecuteContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgExecuteContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgExecuteContractResponse) ProtoMessage() {}

func (x *MsgExecuteContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgExecuteContractResponse.ProtoReflect.Descriptor instead.
func (*MsgExecuteContractResponse) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgExecuteContractResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// MsgMigrateContract runs a code upgrade/ downgrade for a smart contract
type MsgMigrateContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender is the that actor that signed the messages
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Contract is the address of the smart contract
	Contract string `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	// CodeID references the new WASM code
	CodeId uint64 `protobuf:"varint,3,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// Msg json encoded message to be passed to the contract on migration
	Msg []byte `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgMigrateContract) Reset() {
	*x = MsgMigrateContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMigrateContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMigrateContract) ProtoMessage() {}

func (x *MsgMigrateContract) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMigrateContract.ProtoReflect.Descriptor instead.
func (*MsgMigrateContract) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgMigrateContract) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgMigrateContract) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *MsgMigrateContract) GetCodeId() uint64 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *MsgMigrateContract) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

// MsgMigrateContractResponse returns contract migration result data.
type MsgMigrateContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data contains same raw bytes returned as data from the wasm contract.
	// (May be empty)
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MsgMigrateContractResponse) Reset() {
	*x = MsgMigrateContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMigrateContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMigrateContractResponse) ProtoMessage() {}

func (x *MsgMigrateContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMigrateContractResponse.ProtoReflect.Descriptor instead.
func (*MsgMigrateContractResponse) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MsgMigrateContractResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// MsgUpdateAdmin sets a new admin for a smart contract
type MsgUpdateAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender is the that actor that signed the messages
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// NewAdmin address to be set
	NewAdmin string `protobuf:"bytes,2,opt,name=new_admin,json=newAdmin,proto3" json:"new_admin,omitempty"`
	// Contract is the address of the smart contract
	Contract string `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (x *MsgUpdateAdmin) Reset() {
	*x = MsgUpdateAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUpdateAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateAdmin) ProtoMessage() {}

func (x *MsgUpdateAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateAdmin.ProtoReflect.Descriptor instead.
func (*MsgUpdateAdmin) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MsgUpdateAdmin) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgUpdateAdmin) GetNewAdmin() string {
	if x != nil {
		return x.NewAdmin
	}
	return ""
}

func (x *MsgUpdateAdmin) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

// MsgUpdateAdminResponse returns empty data
type MsgUpdateAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgUpdateAdminResponse) Reset() {
	*x = MsgUpdateAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUpdateAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateAdminResponse) ProtoMessage() {}

func (x *MsgUpdateAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateAdminResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateAdminResponse) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{11}
}

// MsgClearAdmin removes any admin stored for a smart contract
type MsgClearAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sender is the that actor that signed the messages
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Contract is the address of the smart contract
	Contract string `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
}

func (x *MsgClearAdmin) Reset() {
	*x = MsgClearAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgClearAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgClearAdmin) ProtoMessage() {}

func (x *MsgClearAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgClearAdmin.ProtoReflect.Descriptor instead.
func (*MsgClearAdmin) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{12}
}

func (x *MsgClearAdmin) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgClearAdmin) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

// MsgClearAdminResponse returns empty data
type MsgClearAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgClearAdminResponse) Reset() {
	*x = MsgClearAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgClearAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgClearAdminResponse) ProtoMessage() {}

func (x *MsgClearAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmwasm_wasm_v1_tx_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgClearAdminResponse.ProtoReflect.Descriptor instead.
func (*MsgClearAdminResponse) Descriptor() ([]byte, []int) {
	return file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP(), []int{13}
}

var File_cosmwasm_wasm_v1_tx_proto protoreflect.FileDescriptor

var file_cosmwasm_wasm_v1_tx_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x2f,
	0x76, 0x31, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x6f, 0x73,
	0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x63,
	0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x0c, 0x4d,
	0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x77, 0x61, 0x73,
	0x6d, 0x42, 0x79, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x4a,
	0x04, 0x08, 0x04, 0x10, 0x05, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x06, 0x22, 0x4b, 0x0a, 0x14, 0x4d,
	0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x22, 0xb8, 0x01, 0x0a, 0x16, 0x4d, 0x73, 0x67,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x2f, 0x0a, 0x05, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x05, 0x66, 0x75,
	0x6e, 0x64, 0x73, 0x22, 0xe6, 0x01, 0x0a, 0x17, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x32, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x63, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2f,
	0x0a, 0x05, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x05, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x69, 0x78, 0x4d, 0x73, 0x67, 0x22, 0x4e, 0x0a, 0x1e,
	0x4d, 0x73, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x1f,
	0x4d, 0x73, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8b, 0x01,
	0x0a, 0x12, 0x4d, 0x73, 0x67, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2f, 0x0a, 0x05, 0x66, 0x75,
	0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x43, 0x6f, 0x69, 0x6e, 0x52, 0x05, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x1a, 0x4d,
	0x73, 0x67, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x73, 0x0a,
	0x12, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x30, 0x0a, 0x1a, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x4d, 0x73, 0x67, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x43, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xc4, 0x05, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x53, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e,
	0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e,
	0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x13,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77,
	0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x30, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x74, 0x0a, 0x14, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x32, 0x12, 0x29, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61,
	0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x69, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x32, 0x1a, 0x31, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61,
	0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x69, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x32, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77,
	0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x2c,
	0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x73, 0x67, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x0f,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12,
	0x24, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d,
	0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61,
	0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x28, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e,
	0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1f, 0x2e, 0x63,
	0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x73, 0x67, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x27, 0x2e,
	0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x73, 0x67, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xc1, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x76, 0x31, 0x42,
	0x07, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x79, 0x33, 0x72, 0x6c, 0x61, 0x62, 0x73,
	0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x6d,
	0x2f, 0x76, 0x31, 0x3b, 0x77, 0x61, 0x73, 0x6d, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x57, 0x58,
	0xaa, 0x02, 0x10, 0x43, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x57, 0x61, 0x73, 0x6d,
	0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x43, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d, 0x5c, 0x57,
	0x61, 0x73, 0x6d, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x43, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73,
	0x6d, 0x5c, 0x57, 0x61, 0x73, 0x6d, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x43, 0x6f, 0x73, 0x6d, 0x77, 0x61, 0x73, 0x6d,
	0x3a, 0x3a, 0x57, 0x61, 0x73, 0x6d, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cosmwasm_wasm_v1_tx_proto_rawDescOnce sync.Once
	file_cosmwasm_wasm_v1_tx_proto_rawDescData = file_cosmwasm_wasm_v1_tx_proto_rawDesc
)

func file_cosmwasm_wasm_v1_tx_proto_rawDescGZIP() []byte {
	file_cosmwasm_wasm_v1_tx_proto_rawDescOnce.Do(func() {
		file_cosmwasm_wasm_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmwasm_wasm_v1_tx_proto_rawDescData)
	})
	return file_cosmwasm_wasm_v1_tx_proto_rawDescData
}

var file_cosmwasm_wasm_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cosmwasm_wasm_v1_tx_proto_goTypes = []interface{}{
	(*MsgStoreCode)(nil),                    // 0: cosmwasm.wasm.v1.MsgStoreCode
	(*MsgStoreCodeResponse)(nil),            // 1: cosmwasm.wasm.v1.MsgStoreCodeResponse
	(*MsgInstantiateContract)(nil),          // 2: cosmwasm.wasm.v1.MsgInstantiateContract
	(*MsgInstantiateContract2)(nil),         // 3: cosmwasm.wasm.v1.MsgInstantiateContract2
	(*MsgInstantiateContractResponse)(nil),  // 4: cosmwasm.wasm.v1.MsgInstantiateContractResponse
	(*MsgInstantiateContract2Response)(nil), // 5: cosmwasm.wasm.v1.MsgInstantiateContract2Response
	(*MsgExecuteContract)(nil),              // 6: cosmwasm.wasm.v1.MsgExecuteContract
	(*MsgExecuteContractResponse)(nil),      // 7: cosmwasm.wasm.v1.MsgExecuteContractResponse
	(*MsgMigrateContract)(nil),              // 8: cosmwasm.wasm.v1.MsgMigrateContract
	(*MsgMigrateContractResponse)(nil),      // 9: cosmwasm.wasm.v1.MsgMigrateContractResponse
	(*MsgUpdateAdmin)(nil),                  // 10: cosmwasm.wasm.v1.MsgUpdateAdmin
	(*MsgUpdateAdminResponse)(nil),          // 11: cosmwasm.wasm.v1.MsgUpdateAdminResponse
	(*MsgClearAdmin)(nil),                   // 12: cosmwasm.wasm.v1.MsgClearAdmin
	(*MsgClearAdminResponse)(nil),           // 13: cosmwasm.wasm.v1.MsgClearAdminResponse
	(*v1beta1.Coin)(nil),                    // 14: cosmos.base.v1beta1.Coin
}
var file_cosmwasm_wasm_v1_tx_proto_depIdxs = []int32{
	14, // 0: cosmwasm.wasm.v1.MsgInstantiateContract.funds:type_name -> cosmos.base.v1beta1.Coin
	14, // 1: cosmwasm.wasm.v1.MsgInstantiateContract2.funds:type_name -> cosmos.base.v1beta1.Coin
	14, // 2: cosmwasm.wasm.v1.MsgExecuteContract.funds:type_name -> cosmos.base.v1beta1.Coin
	0,  // 3: cosmwasm.wasm.v1.Msg.StoreCode:input_type -> cosmwasm.wasm.v1.MsgStoreCode
	2,  // 4: cosmwasm.wasm.v1.Msg.InstantiateContract:input_type -> cosmwasm.wasm.v1.MsgInstantiateContract
	3,  // 5: cosmwasm.wasm.v1.Msg.InstantiateContract2:input_type -> cosmwasm.wasm.v1.MsgInstantiateContract2
	6,  // 6: cosmwasm.wasm.v1.Msg.ExecuteContract:input_type -> cosmwasm.wasm.v1.MsgExecuteContract
	8,  // 7: cosmwasm.wasm.v1.Msg.MigrateContract:input_type -> cosmwasm.wasm.v1.MsgMigrateContract
	10, // 8: cosmwasm.wasm.v1.Msg.UpdateAdmin:input_type -> cosmwasm.wasm.v1.MsgUpdateAdmin
	12, // 9: cosmwasm.wasm.v1.Msg.ClearAdmin:input_type -> cosmwasm.wasm.v1.MsgClearAdmin
	1,  // 10: cosmwasm.wasm.v1.Msg.StoreCode:output_type -> cosmwasm.wasm.v1.MsgStoreCodeResponse
	4,  // 11: cosmwasm.wasm.v1.Msg.InstantiateContract:output_type -> cosmwasm.wasm.v1.MsgInstantiateContractResponse
	5,  // 12: cosmwasm.wasm.v1.Msg.InstantiateContract2:output_type -> cosmwasm.wasm.v1.MsgInstantiateContract2Response
	7,  // 13: cosmwasm.wasm.v1.Msg.ExecuteContract:output_type -> cosmwasm.wasm.v1.MsgExecuteContractResponse
	9,  // 14: cosmwasm.wasm.v1.Msg.MigrateContract:output_type -> cosmwasm.wasm.v1.MsgMigrateContractResponse
	11, // 15: cosmwasm.wasm.v1.Msg.UpdateAdmin:output_type -> cosmwasm.wasm.v1.MsgUpdateAdminResponse
	13, // 16: cosmwasm.wasm.v1.Msg.ClearAdmin:output_type -> cosmwasm.wasm.v1.MsgClearAdminResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cosmwasm_wasm_v1_tx_proto_init() }
func file_cosmwasm_wasm_v1_tx_proto_init() {
	if File_cosmwasm_wasm_v1_tx_proto != nil {
		return
	}
	file_cosmwasm_wasm_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStoreCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgStoreCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInstantiateContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInstantiateContract2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInstantiateContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInstantiateContract2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgExecuteContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgExecuteContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMigrateContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMigrateContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUpdateAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUpdateAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgClearAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cosmwasm_wasm_v1_tx_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgClearAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmwasm_wasm_v1_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cosmwasm_wasm_v1_tx_proto_goTypes,
		DependencyIndexes: file_cosmwasm_wasm_v1_tx_proto_depIdxs,
		MessageInfos:      file_cosmwasm_wasm_v1_tx_proto_msgTypes,
	}.Build()
	File_cosmwasm_wasm_v1_tx_proto = out.File
	file_cosmwasm_wasm_v1_tx_proto_rawDesc = nil
	file_cosmwasm_wasm_v1_tx_proto_goTypes = nil
	file_cosmwasm_wasm_v1_tx_proto_depIdxs = nil
}
