#!/bin/bash
# scripts/testnet.sh — 3-node Layer testnet orchestration script
#
# Launches a 3-node slay3rd testnet on localhost for integration testing.
# Each node runs on a different port pair (P2P + gRPC) with separate WAL dirs.
#
# Usage:
#   scripts/testnet.sh [start]   — Build, keygen, create configs, launch nodes
#   scripts/testnet.sh stop      — Kill all running slay3rd processes
#   scripts/testnet.sh status    — Print running status and latest block heights
#   scripts/testnet.sh wait <N>  — Wait until all nodes have reached block height N
#
# Requires: cargo in PATH (for build and keygen tool)
# SLAY_LOG can be set to control log verbosity (default: info)

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

TESTNET_DIR="${TESTNET_DIR:-/tmp/layer-testnet}"
NUM_VALIDATORS=3
SDK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SLAY3RD="${SDK_ROOT}/target/release/slay3rd"
KEYGEN_MANIFEST="${SDK_ROOT}/tools/generate-testnet-keys/Cargo.toml"
RUST_LOG="${SLAY_LOG:-info}"

# Port allocation:
#   Node 0: P2P=26656, gRPC=9090
#   Node 1: P2P=26657, gRPC=9091
#   Node 2: P2P=26658, gRPC=9092
P2P_BASE=26656
GRPC_BASE=9090

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

log() { echo "[testnet.sh] $*"; }
die() { echo "[testnet.sh] ERROR: $*" >&2; exit 1; }

node_dir() { echo "${TESTNET_DIR}/node-${1}"; }

pid_file() { echo "${TESTNET_DIR}/node-${1}/node.pid"; }

log_file() { echo "${TESTNET_DIR}/node-${1}/node.log"; }

key_file() { echo "${TESTNET_DIR}/validator-${1}/keys.json"; }

node_running() {
    local pid_f
    pid_f="$(pid_file "$1")"
    [[ -f "$pid_f" ]] && kill -0 "$(cat "$pid_f")" 2>/dev/null
}

wait_for_height() {
    local target_height="$1"
    local timeout_secs="${2:-120}"
    local elapsed=0

    log "Waiting for all nodes to reach block height ${target_height} (timeout: ${timeout_secs}s)..."

    while [[ $elapsed -lt $timeout_secs ]]; do
        local all_at_height=true
        for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
            local log_f
            log_f="$(log_file "$i")"
            if [[ ! -f "$log_f" ]]; then
                all_at_height=false
                break
            fi
            # Parse "height=N" from structured tracing output
            local latest_height
            latest_height=$(grep -oP 'height=\K[0-9]+' "$log_f" 2>/dev/null | tail -1 || echo "0")
            if [[ -z "$latest_height" ]] || [[ "$latest_height" -lt "$target_height" ]]; then
                all_at_height=false
                break
            fi
        done

        if $all_at_height; then
            log "All nodes reached block height ${target_height}."
            return 0
        fi

        sleep 2
        elapsed=$((elapsed + 2))
    done

    log "WARNING: Timed out waiting for block height ${target_height} after ${timeout_secs}s"
    return 1
}

# ---------------------------------------------------------------------------
# Command: start
# ---------------------------------------------------------------------------

cmd_start() {
    log "=== Starting 3-node Layer testnet ==="

    # Step 1: Build slay3rd binary
    log "Building slay3rd (release)..."
    cargo build -p slay3rd --release --manifest-path "${SDK_ROOT}/Cargo.toml" \
        2>&1 | tail -5
    [[ -f "$SLAY3RD" ]] || die "slay3rd binary not found at ${SLAY3RD}"
    log "Build complete: ${SLAY3RD}"

    # Step 2: Generate testnet key material
    log "Generating testnet key material for ${NUM_VALIDATORS} validators..."
    mkdir -p "${TESTNET_DIR}"
    cargo run --manifest-path "${KEYGEN_MANIFEST}" -- \
        --output-dir "${TESTNET_DIR}" \
        --validators "${NUM_VALIDATORS}" \
        2>&1
    log "Key generation complete."

    # Step 3: Create node directories and config files
    for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
        local dir p2p_port grpc_port
        dir="$(node_dir "$i")"
        p2p_port=$((P2P_BASE + i))
        grpc_port=$((GRPC_BASE + i))

        mkdir -p "${dir}/data/wal"

        # Build peers list (all validators except self)
        local peers=""
        for j in $(seq 0 $((NUM_VALIDATORS - 1))); do
            if [[ "$j" != "$i" ]]; then
                local peer_p2p_port=$((P2P_BASE + j))
                if [[ -n "$peers" ]]; then
                    peers="${peers}, \"127.0.0.1:${peer_p2p_port}\""
                else
                    peers="\"127.0.0.1:${peer_p2p_port}\""
                fi
            fi
        done

        # Write TOML config
        cat > "${dir}/config.toml" <<TOML
# slay3rd node ${i} config — auto-generated by scripts/testnet.sh
validator_index = ${i}
chain_id = "slay3r-testnet-1"
p2p_listen = "127.0.0.1:${p2p_port}"
grpc_listen = "127.0.0.1:${grpc_port}"
peers = [${peers}]
bls_key_path = "${TESTNET_DIR}/validator-${i}/keys.json"
identity_key_path = "${TESTNET_DIR}/validator-${i}/keys.json"
rocksdb_path = "${dir}/data/rocksdb"
wal_path = "${dir}/data/wal"
genesis_path = "${TESTNET_DIR}/genesis.json"
mempool_max_pending = 10000
leader_timeout_ms = 3000
certification_timeout_ms = 5000
TOML
        log "  Node ${i}: config at ${dir}/config.toml (P2P=:${p2p_port}, gRPC=:${grpc_port})"
    done

    # Step 4: Create shared genesis.json
    cat > "${TESTNET_DIR}/genesis.json" <<'JSON'
{
  "chain_id": "slay3r-testnet-1",
  "initial_height": 1,
  "app_state": {
    "bank": [],
    "wasm": {
      "gov_account": "layer1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmt53rug"
    }
  }
}
JSON
    log "Genesis file written to ${TESTNET_DIR}/genesis.json"

    # Step 5: Launch all 3 nodes in the background
    for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
        local dir log_f pid_f
        dir="$(node_dir "$i")"
        log_f="$(log_file "$i")"
        pid_f="$(pid_file "$i")"

        # Kill any stale process from previous run
        if [[ -f "$pid_f" ]]; then
            local old_pid
            old_pid="$(cat "$pid_f")"
            if kill -0 "$old_pid" 2>/dev/null; then
                log "  Stopping stale node ${i} (PID ${old_pid})"
                kill "$old_pid" 2>/dev/null || true
                sleep 1
            fi
            rm -f "$pid_f"
        fi

        log "  Launching node ${i}..."
        RUST_LOG="${RUST_LOG}" \
            "${SLAY3RD}" "${dir}/config.toml" \
            > "$log_f" 2>&1 &
        echo "$!" > "$pid_f"
        log "  Node ${i} started — PID: $(cat "$pid_f"), log: ${log_f}"
    done

    log ""
    log "All ${NUM_VALIDATORS} nodes launched."
    log "To monitor: tail -f ${TESTNET_DIR}/node-0/node.log"
    log "To stop: $0 stop"
    log "To verify consensus: scripts/verify-consensus.sh"
}

# ---------------------------------------------------------------------------
# Command: stop
# ---------------------------------------------------------------------------

cmd_stop() {
    log "=== Stopping testnet ==="
    local stopped=0

    for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
        local pid_f
        pid_f="$(pid_file "$i")"
        if [[ -f "$pid_f" ]]; then
            local pid
            pid="$(cat "$pid_f")"
            if kill -0 "$pid" 2>/dev/null; then
                log "  Stopping node ${i} (PID ${pid})"
                kill "$pid" 2>/dev/null || true
                stopped=$((stopped + 1))
            else
                log "  Node ${i} (PID ${pid}) already stopped"
            fi
            rm -f "$pid_f"
        else
            log "  Node ${i}: no PID file found"
        fi
    done

    log "Stopped ${stopped} node(s)."
}

# ---------------------------------------------------------------------------
# Command: status
# ---------------------------------------------------------------------------

cmd_status() {
    log "=== Testnet status ==="
    for i in $(seq 0 $((NUM_VALIDATORS - 1))); do
        local pid_f log_f
        pid_f="$(pid_file "$i")"
        log_f="$(log_file "$i")"

        if node_running "$i"; then
            local pid latest_height
            pid="$(cat "$pid_f")"
            latest_height=$(grep -oP 'height=\K[0-9]+' "$log_f" 2>/dev/null | tail -1 || echo "unknown")
            log "  Node ${i}: RUNNING (PID ${pid}), latest block height: ${latest_height}"
        else
            log "  Node ${i}: STOPPED"
        fi
    done
}

# ---------------------------------------------------------------------------
# Command: wait <height>
# ---------------------------------------------------------------------------

cmd_wait() {
    local target="${1:-20}"
    wait_for_height "$target"
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

case "${1:-start}" in
    start)
        cmd_start
        ;;
    stop)
        cmd_stop
        ;;
    status)
        cmd_status
        ;;
    wait)
        cmd_wait "${2:-20}"
        ;;
    *)
        echo "Usage: $0 {start|stop|status|wait [height]}"
        exit 1
        ;;
esac
